// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 实现音频服务，管理游戏音效播放

import 'package:audioplayers/audioplayers.dart';
import '../exceptions/app_exceptions.dart';
import '../services/logger_service.dart';

/// 音效类型
enum SoundType {
  /// 选中棋子
  select,

  /// 移动棋子
  move,

  /// 吃子
  capture,

  /// 胜利
  win,

  /// 失败
  lose,

  /// 按钮点击
  click,
}

/// 音频服务
///
/// 负责游戏音效的播放和管理
class AudioService {
  static final AudioService _instance = AudioService._internal();
  factory AudioService() => _instance;
  AudioService._internal() : _playerFactory = AudioPlayer.new;

  AudioService.forTesting({required AudioPlayer Function() playerFactory})
      : _playerFactory = playerFactory;

  final AudioPlayer Function() _playerFactory;
  Future<void>? _initialization;
  int _generation = 0;
  final Map<SoundType, Future<void>> _operations = {};

  final Map<SoundType, AudioPlayer> _players = {};
  bool _enabled = true;
  double _volume = 0.7;

  /// 初始化音频服务
  Future<void> initialize() => _initialization ??= _initialize();

  Future<void> _initialize() async {
    try {
      // 为每种音效创建独立的播放器
      for (final type in SoundType.values) {
        _players[type] = _playerFactory();
        await _players[type]!.setVolume(_volume);
        await _players[type]!.setReleaseMode(ReleaseMode.stop);
      }

      // 预加载音效文件
      await _preloadSounds();
      logger.info('音频服务初始化成功', 'AudioService');
    } catch (e) {
      logger.error('音频服务初始化失败', 'AudioService', e);
      throw AudioException('音频服务初始化失败', originalError: e);
    }
  }

  /// 预加载所有音效
  Future<void> _preloadSounds() async {
    final soundFiles = {
      SoundType.select: 'sounds/select.wav',
      SoundType.move: 'sounds/move.wav',
      SoundType.capture: 'sounds/capture.wav',
      SoundType.win: 'sounds/win.wav',
      SoundType.lose: 'sounds/lose.wav',
      SoundType.click: 'sounds/click.wav',
    };

    for (final entry in soundFiles.entries) {
      try {
        await _players[entry.key]!.setSource(AssetSource(entry.value));
      } catch (e) {
        // 音效文件不存在时记录警告
        logger.warning('无法加载音效文件: ${entry.value}', 'AudioService');
      }
    }
  }

  /// 播放音效
  Future<void> playSound(SoundType type) async {
    if (!_enabled) return;
    final generation = _generation;
    await _enqueue(type, () async {
      if (!_enabled || generation != _generation) return;
      final player = _players[type];
      if (player == null) return;
      await player.stop();
      if (!_enabled || generation != _generation) return;
      await player.resume();
    });
  }

  Future<void> _enqueue(SoundType type, Future<void> Function() action) {
    final operation = (_operations[type] ?? Future<void>.value())
        .then((_) => action())
        .catchError((Object error) {
      logger.error('音效操作失败', 'AudioService', error);
    });
    _operations[type] = operation;
    return operation;
  }

  Future<void> stopAll() async {
    _generation++;
    await Future.wait([
      for (final entry in _players.entries)
        _enqueue(entry.key, entry.value.stop),
    ]);
  }

  /// 设置音效开关
  Future<void> setEnabled(bool enabled) async {
    _enabled = enabled;
    if (!enabled) await stopAll();
  }

  /// 获取音效开关状态
  bool isEnabled() => _enabled;

  /// 设置音量
  void setVolume(double volume) {
    _volume = volume.clamp(0.0, 1.0);
    for (final player in _players.values) {
      player.setVolume(_volume);
    }
  }

  /// 获取音量
  double getVolume() => _volume;

  /// 释放资源
  Future<void> dispose() async {
    await stopAll();
    await _initialization;
    for (final player in _players.values) {
      await player.dispose();
    }
    _players.clear();
    _operations.clear();
    _initialization = null;
  }
}
