// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 实现游戏引擎，统筹游戏流程和规则执行

import '../models/board_state.dart';
import '../models/position.dart';
import '../models/piece_type.dart';
import '../models/move.dart';
import '../models/game_result.dart';
import 'move_validator.dart';
import 'capture_detector.dart';

/// 移动结果
class MoveResult {
  /// 移动是否成功
  final bool success;

  /// 移动记录（如果成功）
  final Move? move;

  /// 被吃棋子位置，顺序固定为横向后纵向。
  final List<Position> capturedPieces;

  /// 兼容旧调用方的首个被吃棋子。
  Position? get captured =>
      capturedPieces.isEmpty ? null : capturedPieces.first;

  /// 游戏是否结束
  final bool gameOver;

  /// 游戏结果（如果结束）
  final GameResult? gameResult;

  /// 连续未吃子的独立回合数（ply）。
  final int noCapturePlyCount;

  /// 错误信息（如果失败）
  final String? error;

  /// 新的棋盘状态
  final BoardState? newBoard;

  MoveResult({
    required this.success,
    this.move,
    List<Position> capturedPieces = const [],
    Position? captured,
    this.gameOver = false,
    this.gameResult,
    this.noCapturePlyCount = 0,
    this.error,
    this.newBoard,
  }) : capturedPieces = List.unmodifiable(
          captured == null
              ? capturedPieces
              : <Position>[
                  ...capturedPieces,
                  if (!capturedPieces.contains(captured)) captured,
                ],
        );

  /// 创建成功结果
  factory MoveResult.success({
    required Move move,
    List<Position> capturedPieces = const [],
    Position? captured,
    required bool gameOver,
    GameResult? gameResult,
    int noCapturePlyCount = 0,
    required BoardState newBoard,
  }) {
    return MoveResult(
      success: true,
      move: move,
      capturedPieces: capturedPieces,
      captured: captured,
      gameOver: gameOver,
      gameResult: gameResult,
      noCapturePlyCount: noCapturePlyCount,
      newBoard: newBoard,
    );
  }

  /// 创建失败结果
  factory MoveResult.failure(String error) {
    return MoveResult(
      success: false,
      error: error,
    );
  }
}

/// 游戏引擎
///
/// 负责游戏核心流程：
/// - 移动执行
/// - 吃子检测
/// - 胜负判定
/// - 游戏状态管理
class GameEngine {
  final MoveValidator _validator;
  final CaptureDetector _captureDetector;

  /// 移动历史记录
  final List<Move> _moveHistory = [];

  /// 游戏开始时间
  DateTime? _startTime;

  GameEngine()
      : _validator = MoveValidator(),
        _captureDetector = CaptureDetector();

  /// 开始新游戏
  void startNewGame({DateTime? startedAt}) {
    _moveHistory.clear();
    _startTime = startedAt ?? DateTime.now();
  }

  /// Restores the bookkeeping used for terminal metadata after loading or
  /// rebuilding a game. Board state remains owned by the caller.
  void restoreGame(
    Iterable<Move> moveHistory, {
    DateTime? startedAt,
  }) {
    _moveHistory
      ..clear()
      ..addAll(moveHistory);
    _startTime = startedAt ?? DateTime.now();
  }

  /// 执行移动
  ///
  /// 验证移动合法性，执行移动，检测吃子，更新状态
  /// 执行移动
  ///
  /// 验证移动合法性，执行移动，检测吃子，更新状态
  MoveResult executeMove(
    BoardState board,
    Position from,
    Position to, {
    Position? capturedPieceOverride,
    List<Position>? capturedPiecesOverride,
    int noCapturePlyCount = 0,
  }) {
    // 1. 验证移动合法性
    if (!_validator.isValidMove(board, from, to)) {
      return MoveResult.failure('移动不合法');
    }

    // 2. 执行移动
    var newBoard = board.movePiece(from, to);
    final player = board.currentPlayer;

    // 3. 检测吃子 (如果有Override则优先使用)
    final List<Position> capturedPositions;
    if (capturedPiecesOverride != null) {
      capturedPositions = List.of(capturedPiecesOverride);
    } else if (capturedPieceOverride != null) {
      capturedPositions = [capturedPieceOverride];
    } else {
      capturedPositions = _captureDetector.detectCaptures(
        newBoard,
        movedPiece: to,
        player: player,
      );
    }

    // 4. 横向后纵向一次性移除全部被吃棋子
    for (final capturedPosition in capturedPositions) {
      newBoard = newBoard.removePiece(capturedPosition);
    }
    final nextNoCapturePlyCount =
        capturedPositions.isEmpty ? noCapturePlyCount + 1 : 0;

    // 5. 创建移动记录
    final move = Move.now(
      from: from,
      to: to,
      player: player,
      capturedPieces: capturedPositions,
    );
    _moveHistory.add(move);

    // 6. 检查游戏是否结束
    var gameResult = checkGameOver(
      newBoard,
      noCapturePlyCount: nextNoCapturePlyCount,
    );

    // 7. 棋子数量未触发终局时，先切换到下一方，再判断其是否有路可走。
    if (gameResult == null) {
      newBoard = newBoard.switchPlayer();
      gameResult = checkGameOver(newBoard);
    }
    final gameOver = gameResult != null;

    return MoveResult.success(
      move: move,
      capturedPieces: capturedPositions,
      gameOver: gameOver,
      gameResult: gameResult,
      noCapturePlyCount: nextNoCapturePlyCount,
      newBoard: newBoard,
    );
  }

  /// 检查游戏是否结束
  ///
  /// 判定规则：
  /// 棋子数判负优先，其次是 50 ply 和棋，最后是当前方无合法移动。
  GameResult? checkGameOver(BoardState board, {int noCapturePlyCount = 0}) {
    final blackCount = board.getPieceCount(PieceType.black);
    final whiteCount = board.getPieceCount(PieceType.white);

    final duration = _startTime != null
        ? DateTime.now().difference(_startTime!)
        : Duration.zero;

    // 任一方仅剩一个或更少棋子时立即判负。
    if (blackCount <= 1) {
      return GameResult.whiteWin(
        reason: '黑方仅剩一个或更少棋子',
        moveCount: _moveHistory.length,
        duration: duration,
      );
    }

    if (whiteCount <= 1) {
      return GameResult.blackWin(
        reason: '白方仅剩一个或更少棋子',
        moveCount: _moveHistory.length,
        duration: duration,
      );
    }

    if (noCapturePlyCount >= 50) {
      return GameResult.draw(
        reason: '连续50手未发生吃子',
        endReason: GameEndReason.noCaptureLimit,
        moveCount: _moveHistory.length,
        duration: duration,
      );
    }

    if (!_validator.hasValidMoves(board, board.currentPlayer)) {
      final loser = board.currentPlayer;
      final reason = '${loser.getDisplayName()}无合法移动';
      if (loser == PieceType.black) {
        return GameResult.whiteWin(
          reason: reason,
          endReason: GameEndReason.noLegalMoves,
          moveCount: _moveHistory.length,
          duration: duration,
        );
      }
      return GameResult.blackWin(
        reason: reason,
        endReason: GameEndReason.noLegalMoves,
        moveCount: _moveHistory.length,
        duration: duration,
      );
    }

    // 游戏继续
    return null;
  }

  /// 获取所有可能的移动
  ///
  /// 返回当前玩家所有合法移动
  Map<Position, List<Position>> getPossibleMoves(
    BoardState board,
    PieceType player,
  ) {
    return _validator.getAllPossibleMoves(board, player);
  }

  /// 获取移动历史
  List<Move> get moveHistory => List.unmodifiable(_moveHistory);

  /// 获取游戏时长
  Duration get gameDuration {
    if (_startTime == null) return Duration.zero;
    return DateTime.now().difference(_startTime!);
  }

  /// 模拟移动（不改变实际状态，用于AI）
  ///
  /// 返回移动后的棋盘状态
  BoardState? simulateMove(
    BoardState board,
    Position from,
    Position to,
  ) {
    if (!_validator.isValidMove(board, from, to)) {
      return null;
    }

    var newBoard = board.movePiece(from, to);
    final player = board.currentPlayer;

    // 检测并执行吃子
    final capturedPositions = _captureDetector.detectCaptures(
      newBoard,
      movedPiece: to,
      player: player,
    );

    for (final capturedPosition in capturedPositions) {
      newBoard = newBoard.removePiece(capturedPosition);
    }

    // 切换玩家
    newBoard = newBoard.switchPlayer();

    return newBoard;
  }

  /// 评估棋盘局面（简单版本，用于AI）
  ///
  /// 返回分数，正数表示对player有利
  int evaluateBoard(BoardState board, PieceType player) {
    final opponent = player.getOpponent();

    // 棋子数量差
    final myPieces = board.getPieceCount(player);
    final opponentPieces = board.getPieceCount(opponent);

    return (myPieces - opponentPieces) * 100;
  }

  /// 撤销上一步移动（用于悔棋功能）
  ///
  /// 返回撤销后的棋盘状态，如果无法撤销则返回null
  BoardState? undoLastMove(BoardState currentBoard) {
    if (_moveHistory.isEmpty) {
      return null;
    }

    // 从初始状态重新执行所有移动（除了最后一步）
    final movesToReplay = _moveHistory.take(_moveHistory.length - 1).toList();
    _moveHistory.removeLast();

    var board = BoardState.initial();
    for (final move in movesToReplay) {
      final result = executeMove(board, move.from, move.to);
      if (!result.success || result.newBoard == null) {
        return null;
      }
      board = result.newBoard!;
    }

    return board;
  }

  /// 获取吃子机会
  ///
  /// 返回所有可以吃子的移动
  Map<Position, Map<Position, Position>> getCaptureOpportunities(
    BoardState board,
    PieceType player,
  ) {
    return _captureDetector.getAllCaptureOpportunities(board, player);
  }

  /// 重置游戏引擎
  void reset() {
    _moveHistory.clear();
    _startTime = null;
  }
}
