/// Game Page - 完整游戏页面
///
/// 职责：
/// - 集成GameBloc状态管理
/// - 显示棋盘和游戏信息
/// - 处理用户交互
/// - 响应游戏状态变化
library;

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../l10n/app_localizations.dart';
import '../../bloc/game_bloc.dart';
import '../../bloc/game_event.dart';
import '../../bloc/game_state.dart';
import '../../models/position.dart';
import '../../models/piece_type.dart';
import '../../services/voice/game_voice_session.dart';
import '../../theme/theme_pack.dart';
import '../../theme/theme_pack_registry.dart';
import '../widgets/themed_board_widget.dart'; // 暂时使用静态棋盘替代动画棋盘
import '../widgets/game_info_panel.dart';
import '../widgets/game_over_dialog.dart';
import '../widgets/first_player_indicator.dart';
import 'game_replay_page.dart'; // 导入回放页面

/// 游戏页面
class GamePage extends StatelessWidget {
  final GameMode mode;
  final String? aiDifficulty;
  final bool resumeSavedGame;
  final GameVoiceSessionFactory? voiceSessionFactory;

  const GamePage({
    super.key,
    this.mode = GameMode.pvp,
    this.aiDifficulty,
    this.resumeSavedGame = false,
    this.voiceSessionFactory,
  });

  /// Hidden production composition for the Phase 4 PVE voice capability.
  ///
  /// The factory itself remains lazy and is not invoked until the player reads
  /// the disclosure and explicitly enables voice on their real PVE turn.
  factory GamePage.voice({
    Key? key,
    GameMode mode = GameMode.pve,
    String? aiDifficulty,
    bool resumeSavedGame = false,
  }) {
    return GamePage(
      key: key,
      mode: mode,
      aiDifficulty: aiDifficulty,
      resumeSavedGame: resumeSavedGame,
      voiceSessionFactory: createProductionGameVoiceSession,
    );
  }

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) {
        final bloc = GameBloc();
        if (resumeSavedGame) {
          bloc.add(const LoadGameEvent());
        } else {
          bloc.add(
            NewGameEvent(
              mode: mode,
              aiDifficulty: aiDifficulty,
            ),
          );
        }
        return bloc;
      },
      child: GamePageView(voiceSessionFactory: voiceSessionFactory),
    );
  }
}

class GamePageView extends StatefulWidget {
  const GamePageView({
    super.key,
    this.voiceSessionFactory,
  });

  final GameVoiceSessionFactory? voiceSessionFactory;

  @override
  State<GamePageView> createState() => _GamePageViewState();
}

class _GamePageViewState extends State<GamePageView>
    with WidgetsBindingObserver {
  // Generated by Qoder AI (Model: gemini-3-pro) - 2025-11-25
  // Task: 添加先手方提示动画显示状态控制

  /// 是否显示先手方提示动画
  bool _showFirstPlayerIndicator = false;

  /// 先手方
  PieceType? _firstPlayer;
  Timer? _displayTicker;
  final ThemePack _themePack = ThemePackRegistry.phaseOne().defaultPack;
  GameVoiceSession? _voiceSession;
  StreamSubscription<VoiceInteractionState>? _voiceSubscription;
  VoiceInteractionState _voiceState =
      const VoiceInteractionState(VoiceInteractionPhase.disabled);
  bool _voiceBusy = false;
  bool _voiceSetupFailed = false;
  bool _appIsActive = true;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _displayTicker = Timer.periodic(const Duration(seconds: 1), (_) {
      if (mounted) setState(() {});
    });
    // 在下一帧检查是否需要显示先手提示
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _checkFirstPlayerIndicator();
    });
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    final bloc = context.read<GameBloc>();
    final now = DateTime.now();
    switch (state) {
      case AppLifecycleState.resumed:
        _appIsActive = true;
        unawaited(
          _voiceSession?.updateAvailability(appIsActive: true),
        );
        bloc.add(ResumeTurnClockEvent(now));
        return;
      case AppLifecycleState.inactive:
      case AppLifecycleState.hidden:
      case AppLifecycleState.paused:
      case AppLifecycleState.detached:
        _appIsActive = false;
        unawaited(
          _voiceSession?.updateAvailability(appIsActive: false),
        );
        bloc.add(PauseTurnClockEvent(now));
        return;
    }
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _displayTicker?.cancel();
    unawaited(_voiceSubscription?.cancel());
    unawaited(_voiceSession?.dispose());
    super.dispose();
  }

  /// 检查是否需要显示先手提示
  void _checkFirstPlayerIndicator() {
    final state = context.read<GameBloc>().state;
    if (state is GamePlaying &&
        state.firstPlayer != null &&
        state.mode == GameMode.pvp) {
      setState(() {
        _firstPlayer = state.firstPlayer;
        _showFirstPlayerIndicator = true;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    final l10n = AppLocalizations.of(context)!;
    return Scaffold(
      appBar: AppBar(
        title: Text(l10n.gameTitle),
        centerTitle: true,
      ),
      body: Stack(
        children: [
          BlocConsumer<GameBloc, GameState>(
            listener: (context, state) {
              _onGameStateChanged(state);
              // 监听游戏结束状态
              if (state is GameOver) {
                _showGameOverDialog(context, state);
              }
            },
            builder: (context, state) {
              if (state is GameInitial || state is GameLoading) {
                return const Center(
                  child: CircularProgressIndicator(),
                );
              }

              if (state is GameError) {
                return LayoutBuilder(
                  builder: (context, constraints) => SingleChildScrollView(
                    padding: const EdgeInsets.all(16),
                    child: ConstrainedBox(
                      constraints: BoxConstraints(
                        minHeight: constraints.maxHeight > 32
                            ? constraints.maxHeight - 32
                            : 0,
                      ),
                      child: Center(
                        child: ConstrainedBox(
                          constraints: const BoxConstraints(maxWidth: 480),
                          child: Card(
                            child: Padding(
                              padding: const EdgeInsets.all(28),
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  Icon(
                                    Icons.error_outline_rounded,
                                    size: 56,
                                    color: scheme.error,
                                  ),
                                  const SizedBox(height: 16),
                                  Text(
                                    l10n.gameUnavailable,
                                    style: theme.textTheme.titleLarge,
                                  ),
                                  const SizedBox(height: 20),
                                  FilledButton.icon(
                                    onPressed: () {
                                      context
                                          .read<GameBloc>()
                                          .add(const RestartGameEvent());
                                    },
                                    icon: const Icon(Icons.refresh_rounded),
                                    label: Text(l10n.restart),
                                  ),
                                ],
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                );
              }

              // GamePlaying 或 GameOver 状态
              return _buildGameContent(context, state);
            },
          ),
          // Generated by Qoder AI (Model: gemini-3-pro) - 2025-11-25
          // Task: 显示先手方提示动画覆盖层
          if (_showFirstPlayerIndicator && _firstPlayer != null)
            Container(
              color: Colors.black.withValues(alpha: 0.5),
              child: Center(
                child: FirstPlayerIndicator(
                  firstPlayer: _firstPlayer!,
                  onAnimationComplete: () {
                    setState(() {
                      _showFirstPlayerIndicator = false;
                    });
                  },
                ),
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildGameContent(BuildContext context, GameState state) {
    return LayoutBuilder(
      builder: (context, constraints) {
        final isLandscape = constraints.maxWidth > constraints.maxHeight;

        if (isLandscape) {
          // 横屏布局：棋盘在左，信息面板在右
          return Row(
            children: [
              Expanded(
                flex: 2,
                child: Center(
                  child: _buildBoard(context, state),
                ),
              ),
              Expanded(
                flex: 1,
                child: SingleChildScrollView(
                  padding: const EdgeInsets.all(16),
                  child: _buildInfoPanel(context, state),
                ),
              ),
            ],
          );
        } else {
          // 竖屏布局：棋盘在上，信息面板在下
          return Column(
            children: [
              Expanded(
                flex: 2,
                child: Center(
                  child: _buildBoard(context, state),
                ),
              ),
              Expanded(
                flex: 1,
                child: SingleChildScrollView(
                  padding: const EdgeInsets.all(16),
                  child: _buildInfoPanel(context, state),
                ),
              ),
            ],
          );
        }
      },
    );
  }

  Widget _buildBoard(BuildContext context, GameState state) {
    // Generated by Qoder AI (Model: gemini-3-pro) - 2025-11-25
    // Task: 根据先手方和当前玩家决定是否翻转棋盘视角

    // 双人对战按真实先手翻转；人机对战按真实玩家执色翻转。
    // 信息面板复用同一结果，保证移动历史坐标与用户看到的棋盘一致。
    return ThemedBoardWidget(
      boardState: state.boardState,
      selectedPiece: state.selectedPiece,
      validMoves: state.validMoves,
      lastMoveFrom: state.lastMove?.from,
      lastMoveTo: state.lastMove?.to,
      capturedPiecePositions: state.lastMove?.capturedPieces ?? const [],
      flipBoard: _shouldFlipBoard(state),
      onPositionTapped: (position) => _handlePositionTapped(context, position),
    );
  }

  Widget _buildInfoPanel(BuildContext context, GameState state) {
    final isAIThinking = state is GamePlaying && state.isAIThinking;
    final aiProgress = state is GamePlaying ? state.aiThinkingProgress : 0.0;
    final aiStatus = state is GamePlaying ? state.aiThinkingStatus : '';

    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        GameInfoPanel(
          currentPlayer: state.currentPlayer,
          blackPieceCount: state.blackPieceCount,
          whitePieceCount: state.whitePieceCount,
          moveHistory: state.moveHistory,
          canUndo: state.canUndo && !isAIThinking,
          canRedo: state.canRedo && !isAIThinking,
          flipBoard: _shouldFlipBoard(state),
          isAIThinking: isAIThinking,
          aiThinkingProgress: aiProgress,
          aiThinkingStatus: aiStatus,
          turnRemaining:
              state.turnClock?.remainingAt(DateTime.now()) ?? Duration.zero,
          onUndo: () {
            context.read<GameBloc>().add(const UndoMoveEvent());
          },
          onRedo: () {
            context.read<GameBloc>().add(const RedoMoveEvent());
          },
          onRestart: () {
            _showRestartConfirmation(context);
          },
        ),
        if (_supportsVoice(state)) ...[
          const SizedBox(height: 14),
          _buildVoicePanel(context, state as GamePlaying),
        ],
      ],
    );
  }

  bool _shouldFlipBoard(GameState state) {
    if (state.mode == GameMode.pvp && state is GamePlaying) {
      return state.firstPlayer == PieceType.white;
    }
    if (state.mode == GameMode.pve) {
      return state.humanPlayer == PieceType.white;
    }
    return false;
  }

  bool _supportsVoice(GameState state) {
    return widget.voiceSessionFactory != null &&
        state is GamePlaying &&
        state.mode == GameMode.pve &&
        state.humanPlayer != null;
  }

  bool _canStartVoice(GamePlaying state) {
    return _appIsActive &&
        state.currentPlayer == state.humanPlayer &&
        !state.isAIThinking;
  }

  Widget _buildVoicePanel(BuildContext context, GamePlaying state) {
    final l10n = AppLocalizations.of(context)!;
    final colors = _themePack.colors;
    final session = _voiceSession;
    final canStart = _canStartVoice(state);
    final status = session == null
        ? (_voiceSetupFailed
            ? l10n.gameVoiceSetupFailed
            : (canStart
                ? l10n.meditationVoiceDisabled
                : l10n.gameVoiceWaitForTurn))
        : _voiceStatus(l10n, _voiceState);

    return Semantics(
      key: const Key('game-voice-panel'),
      container: true,
      liveRegion: true,
      child: Container(
        padding: const EdgeInsets.all(18),
        decoration: BoxDecoration(
          color: colors.jade.withValues(alpha: 0.08),
          borderRadius: BorderRadius.circular(20),
          border: Border.all(color: colors.jade.withValues(alpha: 0.3)),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(Icons.hearing_rounded, color: colors.jade),
                const SizedBox(width: 10),
                Expanded(
                  child: Text(
                    l10n.gameVoiceTitle,
                    style: Theme.of(context).textTheme.titleMedium?.copyWith(
                          color: colors.inkPrimary,
                          fontWeight: FontWeight.w700,
                        ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 10),
            Text(
              status,
              style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                    color: colors.inkMuted,
                    height: 1.45,
                  ),
            ),
            if (session == null) ...[
              Container(
                key: const Key('game-voice-disclosure'),
                margin: const EdgeInsets.only(top: 10),
                child: Text(
                  '${l10n.gameVoiceDisclosureBody}\n'
                  '${l10n.gameVoiceChineseOnly}\n'
                  '${l10n.meditationPrivacyNote}',
                  style: Theme.of(context).textTheme.bodySmall?.copyWith(
                        color: colors.inkMuted,
                        height: 1.45,
                      ),
                ),
              ),
              const SizedBox(height: 14),
              SizedBox(
                key: const Key('game-voice-enable'),
                width: double.infinity,
                child: FilledButton.icon(
                  onPressed: canStart && !_voiceBusy ? _enableVoice : null,
                  icon: const Icon(Icons.mic_none_rounded),
                  label: Text(l10n.gameVoiceEnable),
                  style: FilledButton.styleFrom(
                    minimumSize: const Size.fromHeight(50),
                    backgroundColor: colors.jade,
                    foregroundColor: colors.paperBase,
                  ),
                ),
              ),
            ] else ...[
              const SizedBox(height: 14),
              if (_voiceState.phase == VoiceInteractionPhase.awaitingReplay)
                SizedBox(
                  key: const Key('game-voice-replay'),
                  width: double.infinity,
                  child: FilledButton.icon(
                    onPressed: !_voiceBusy ? _replayVoiceReply : null,
                    icon: const Icon(Icons.replay_rounded),
                    label: Text(l10n.meditationRepeat),
                    style: FilledButton.styleFrom(
                      minimumSize: const Size.fromHeight(50),
                      backgroundColor: colors.jade,
                      foregroundColor: colors.paperBase,
                    ),
                  ),
                )
              else
                SizedBox(
                  key: const Key('game-voice-listen'),
                  width: double.infinity,
                  child: FilledButton.icon(
                    onPressed: canStart && !_voiceBusy && _voiceState.canListen
                        ? _listenOnce
                        : null,
                    icon: const Icon(Icons.graphic_eq_rounded),
                    label: Text(l10n.gameVoiceListen),
                    style: FilledButton.styleFrom(
                      minimumSize: const Size.fromHeight(50),
                      backgroundColor: colors.jade,
                      foregroundColor: colors.paperBase,
                    ),
                  ),
                ),
            ],
          ],
        ),
      ),
    );
  }

  Future<void> _enableVoice() async {
    final bloc = context.read<GameBloc>();
    final latestState = bloc.state;
    if (_voiceBusy ||
        !_supportsVoice(latestState) ||
        !_canStartVoice(latestState as GamePlaying)) {
      return;
    }
    setState(() {
      _voiceBusy = true;
      _voiceSetupFailed = false;
    });
    try {
      final session = widget.voiceSessionFactory!(
        bloc: bloc,
        controlledPlayer: latestState.humanPlayer!,
      );
      _voiceSession = session;
      _voiceState = session.state;
      _voiceSubscription = session.states.listen(_onVoiceStateChanged);
      await session.enableAfterDisclosure();
      if (mounted) setState(() => _voiceState = session.state);
    } catch (_) {
      final failedSession = _voiceSession;
      _voiceSession = null;
      unawaited(_voiceSubscription?.cancel());
      _voiceSubscription = null;
      if (failedSession != null) unawaited(failedSession.dispose());
      if (mounted) setState(() => _voiceSetupFailed = true);
    } finally {
      if (mounted) setState(() => _voiceBusy = false);
    }
  }

  Future<void> _listenOnce() async {
    final session = _voiceSession;
    if (session == null || _voiceBusy) return;
    setState(() => _voiceBusy = true);
    try {
      await session.listenOnce();
    } catch (_) {
      // The session maps operational failures to stable non-sensitive states.
    } finally {
      if (mounted) setState(() => _voiceBusy = false);
    }
  }

  Future<void> _replayVoiceReply() async {
    final session = _voiceSession;
    if (session == null || _voiceBusy) return;
    setState(() => _voiceBusy = true);
    try {
      await session.replayPendingReply();
    } catch (_) {
      // The session maps replay failures to stable non-sensitive states.
    } finally {
      if (mounted) setState(() => _voiceBusy = false);
    }
  }

  void _onVoiceStateChanged(VoiceInteractionState state) {
    if (mounted) setState(() => _voiceState = state);
  }

  void _onGameStateChanged(GameState state) {
    final session = _voiceSession;
    if (session == null) return;
    unawaited(
      session.updateAvailability(
        appIsActive: _appIsActive,
      ),
    );
  }

  String _voiceStatus(
    AppLocalizations l10n,
    VoiceInteractionState state,
  ) {
    return switch (state.phase) {
      VoiceInteractionPhase.disabled => l10n.meditationVoiceDisabled,
      VoiceInteractionPhase.requestingPermission ||
      VoiceInteractionPhase.initializing =>
        l10n.meditationVoicePreparing,
      VoiceInteractionPhase.ready => l10n.meditationVoiceReady,
      VoiceInteractionPhase.listening => l10n.meditationVoiceListening,
      VoiceInteractionPhase.processing => l10n.meditationVoiceProcessing,
      VoiceInteractionPhase.speaking => l10n.meditationVoiceSpeaking,
      VoiceInteractionPhase.awaitingReplay => l10n.meditationVoiceReplay,
      VoiceInteractionPhase.permissionDenied ||
      VoiceInteractionPhase.permissionPermanentlyDenied ||
      VoiceInteractionPhase.restricted =>
        l10n.meditationVoicePermissionDenied,
      VoiceInteractionPhase.unavailable => l10n.meditationVoiceUnavailable,
      VoiceInteractionPhase.interrupted => l10n.gameVoiceWaitForTurn,
      VoiceInteractionPhase.failed ||
      VoiceInteractionPhase.disposed =>
        l10n.meditationVoiceFailed,
    };
  }

  void _handlePositionTapped(
    BuildContext context,
    Position position,
  ) {
    context.read<GameBloc>().add(ActivateBoardPositionEvent(position));
  }

  void _showGameOverDialog(BuildContext context, GameOver state) {
    final l10n = AppLocalizations.of(context)!;
    WidgetsBinding.instance.addPostFrameCallback((_) {
      showGameOverDialog(
        context,
        winner: state.winner,
        gameResult: state.gameResult!,
        onRestart: () {
          Navigator.of(context).pop();
          context.read<GameBloc>().add(const RestartGameEvent());
        },
        onExit: () {
          Navigator.of(context).pop();
          Navigator.of(context).pop();
        },
        onReplay: state.moveHistory.isNotEmpty
            ? () {
                Navigator.of(context).pop();
                Navigator.of(context).push(
                  MaterialPageRoute(
                    builder: (context) => GameReplayPage(
                      moveHistory: state.moveHistory,
                      startingPlayer: state.firstPlayer ?? PieceType.black,
                      gameTitle: state.mode == GameMode.pvp
                          ? l10n.pvpReplayTitle
                          : l10n.pveReplayTitle,
                    ),
                  ),
                );
              }
            : null,
      );
    });
  }

  void _showRestartConfirmation(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    showDialog(
      context: context,
      builder: (dialogContext) => AlertDialog(
        title: Text(l10n.restartConfirmTitle),
        content: Text(l10n.restartConfirmBody),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(dialogContext).pop(),
            child: Text(l10n.cancel),
          ),
          TextButton(
            onPressed: () {
              Navigator.of(dialogContext).pop();
              context.read<GameBloc>().add(const RestartGameEvent());
            },
            child: Text(l10n.confirm),
          ),
        ],
      ),
    );
  }
}
