// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 实现首次使用引导流程

import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../../l10n/app_localizations.dart';
import '../widgets/game_icon.dart';
import '../../constants/ui_constants.dart';
import '../../constants/storage_constants.dart';

/// 引导页面
class OnboardingPage extends StatefulWidget {
  const OnboardingPage({super.key});

  @override
  State<OnboardingPage> createState() => _OnboardingPageState();
}

class _OnboardingPageState extends State<OnboardingPage> {
  final PageController _pageController = PageController();
  int _currentPage = 0;

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    return Scaffold(
      body: SafeArea(
        child: Column(
          children: [
            // 跳过按钮
            if (_currentPage == 0)
              Align(
                alignment: Alignment.topRight,
                child: Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: TextButton(
                    onPressed: _completeOnboarding,
                    child: Text(l10n.skip),
                  ),
                ),
              )
            else
              const SizedBox(height: 56),

            // 页面内容
            Expanded(
              child: PageView(
                controller: _pageController,
                onPageChanged: (index) {
                  setState(() {
                    _currentPage = index;
                  });
                },
                children: const [
                  _ScrollableOnboardingPage(child: _WelcomePage()),
                  _ScrollableOnboardingPage(child: _RulesBoardPage()),
                  _ScrollableOnboardingPage(child: _RulesMovementPage()),
                  _ScrollableOnboardingPage(child: _RulesCapturePage()),
                  _ScrollableOnboardingPage(child: _FeaturesPage()),
                ],
              ),
            ),

            // 页面指示器
            _PageIndicator(
              currentPage: _currentPage,
              pageCount: 5,
            ),

            // 导航按钮
            Padding(
              padding: UIConstants.paddingLarge,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  // 上一页按钮
                  if (_currentPage > 0)
                    TextButton.icon(
                      onPressed: () {
                        _pageController.previousPage(
                          duration: UIConstants.pageTransitionDuration,
                          curve: Curves.easeInOut,
                        );
                      },
                      icon: const Icon(Icons.arrow_back),
                      label: Text(l10n.previous),
                    )
                  else
                    const Spacer(),

                  // 下一页/开始按钮
                  FilledButton(
                    onPressed: () {
                      if (_currentPage < 4) {
                        _pageController.nextPage(
                          duration: UIConstants.pageTransitionDuration,
                          curve: Curves.easeInOut,
                        );
                      } else {
                        _completeOnboarding();
                      }
                    },
                    style: ElevatedButton.styleFrom(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 32,
                        vertical: 16,
                      ),
                    ),
                    child: Text(
                      _currentPage < 4 ? l10n.next : l10n.startGame,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _completeOnboarding() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(StorageConstants.keyFirstLaunch, false);

    if (mounted) {
      Navigator.of(context).pushReplacementNamed('/home');
    }
  }
}

class _ScrollableOnboardingPage extends StatefulWidget {
  const _ScrollableOnboardingPage({required this.child});

  final Widget child;

  @override
  State<_ScrollableOnboardingPage> createState() =>
      _ScrollableOnboardingPageState();
}

class _ScrollableOnboardingPageState extends State<_ScrollableOnboardingPage> {
  final ScrollController _scrollController = ScrollController();

  @override
  void dispose() {
    _scrollController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(
      builder: (context, constraints) => Scrollbar(
        controller: _scrollController,
        thumbVisibility: true,
        child: SingleChildScrollView(
          controller: _scrollController,
          physics: const ClampingScrollPhysics(),
          child: ConstrainedBox(
            constraints: BoxConstraints(minHeight: constraints.maxHeight),
            child: widget.child,
          ),
        ),
      ),
    );
  }
}

/// 页面指示器
class _PageIndicator extends StatelessWidget {
  final int currentPage;
  final int pageCount;

  const _PageIndicator({
    required this.currentPage,
    required this.pageCount,
  });

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: List.generate(
        pageCount,
        (index) => Container(
          margin: const EdgeInsets.symmetric(horizontal: 4),
          width: currentPage == index ? 24 : 8,
          height: 8,
          decoration: BoxDecoration(
            color:
                currentPage == index ? scheme.primary : scheme.outlineVariant,
            borderRadius: BorderRadius.circular(4),
          ),
        ),
      ),
    );
  }
}

/// 欢迎页
class _WelcomePage extends StatelessWidget {
  const _WelcomePage();

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    return Padding(
      padding: UIConstants.paddingLarge,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          // Logo占位
          Container(
            width: 200,
            height: 200,
            decoration: BoxDecoration(
              color: scheme.surfaceContainer,
              borderRadius:
                  BorderRadius.circular(UIConstants.borderRadiusLarge),
              border: Border.all(color: scheme.outlineVariant),
            ),
            child: const Center(
              child: GameIcon(
                size: 120,
                showPieces: false,
              ),
            ),
          ),
          const SizedBox(height: 32),
          Text(
            l10n.onboardingWelcomeTitle,
            style: theme.textTheme.headlineLarge?.copyWith(
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 16),
          Text(
            l10n.onboardingWelcomeSubtitle,
            style: theme.textTheme.titleMedium?.copyWith(
              color: scheme.onSurfaceVariant,
            ),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 48),
          Text(
            l10n.onboardingWelcomeBody,
            style: theme.textTheme.bodyLarge,
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }
}

/// 棋盘介绍页
class _RulesBoardPage extends StatelessWidget {
  const _RulesBoardPage();

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    final scheme = Theme.of(context).colorScheme;
    return Padding(
      padding: UIConstants.paddingLarge,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(
            l10n.onboardingBoardTitle,
            style: Theme.of(context).textTheme.headlineMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
          ),
          const SizedBox(height: 32),

          // 棋盘示意图
          Container(
            width: 240,
            height: 240,
            decoration: BoxDecoration(
              color: scheme.surfaceContainerHighest,
              borderRadius:
                  BorderRadius.circular(UIConstants.borderRadiusLarge),
              border: Border.all(color: scheme.outlineVariant),
            ),
            child: CustomPaint(
              painter: _BoardDemoPainter(gridColor: scheme.primary),
            ),
          ),

          const SizedBox(height: 32),
          _InfoCard(
            customIcon: Container(
              width: 32,
              height: 32,
              decoration: BoxDecoration(
                color: scheme.primaryContainer,
                borderRadius: BorderRadius.circular(4),
              ),
              child: GameIcon(
                size: 32,
                gridColor: scheme.primary,
                showPieces: false,
              ),
            ),
            title: l10n.onboardingBoardFourByFour,
            description: l10n.onboardingBoardFourByFourDescription,
          ),
          const SizedBox(height: 16),
          _InfoCard(
            icon: Icons.circle,
            title: l10n.onboardingFourPieces,
            description: l10n.onboardingFourPiecesDescription,
          ),
        ],
      ),
    );
  }
}

/// 移动规则页
class _RulesMovementPage extends StatelessWidget {
  const _RulesMovementPage();

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    final scheme = Theme.of(context).colorScheme;
    return Padding(
      padding: UIConstants.paddingLarge,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(
            l10n.onboardingMovementTitle,
            style: Theme.of(context).textTheme.headlineMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
          ),
          const SizedBox(height: 32),

          // 移动示意图
          Container(
            width: 200,
            height: 200,
            decoration: BoxDecoration(
              color: scheme.surfaceContainer,
              borderRadius:
                  BorderRadius.circular(UIConstants.borderRadiusLarge),
            ),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    _DirectionArrow(Icons.arrow_upward),
                  ],
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const _DirectionArrow(Icons.arrow_back),
                    const SizedBox(width: 16),
                    Container(
                      width: 40,
                      height: 40,
                      decoration: const BoxDecoration(
                        color: Colors.black,
                        shape: BoxShape.circle,
                      ),
                    ),
                    const SizedBox(width: 16),
                    const _DirectionArrow(Icons.arrow_forward),
                  ],
                ),
                const Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    _DirectionArrow(Icons.arrow_downward),
                  ],
                ),
              ],
            ),
          ),

          const SizedBox(height: 32),
          _InfoCard(
            icon: Icons.arrow_upward,
            title: l10n.onboardingOrthogonalMove,
            description: l10n.onboardingOrthogonalMoveDescription,
          ),
          const SizedBox(height: 16),
          _InfoCard(
            icon: Icons.block,
            title: l10n.onboardingNoDiagonal,
            description: l10n.onboardingNoDiagonalDescription,
          ),
        ],
      ),
    );
  }
}

/// 吃子规则页
class _RulesCapturePage extends StatelessWidget {
  const _RulesCapturePage();

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    final scheme = Theme.of(context).colorScheme;
    return Padding(
      padding: UIConstants.paddingLarge,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(
            l10n.onboardingCaptureTitle,
            style: Theme.of(context).textTheme.headlineMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
          ),
          const SizedBox(height: 32),

          // 吃子示意图：完整四格“己-己-敌-空”。
          Container(
            width: 240,
            height: 120,
            decoration: BoxDecoration(
              color: scheme.surfaceContainer,
              borderRadius:
                  BorderRadius.circular(UIConstants.borderRadiusLarge),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                _buildPiece(Colors.black, scheme.outline),
                _buildPiece(Colors.black, scheme.outline),
                _buildPiece(Colors.white, scheme.outline),
                Container(
                  width: 32,
                  height: 32,
                  alignment: Alignment.center,
                  decoration: BoxDecoration(
                    border: Border.all(color: scheme.outline),
                    borderRadius: BorderRadius.circular(6),
                  ),
                  child: Text(l10n.emptyCell),
                ),
              ],
            ),
          ),

          const SizedBox(height: 32),
          _InfoCard(
            icon: Icons.grid_4x4,
            title: l10n.onboardingExactPattern,
            description: l10n.onboardingExactPatternDescription,
          ),
          const SizedBox(height: 16),
          _InfoCard(
            icon: Icons.close,
            title: l10n.onboardingMovedPieceParticipates,
            description: l10n.onboardingMovedPieceParticipatesDescription,
          ),
        ],
      ),
    );
  }

  Widget _buildPiece(
    Color color,
    Color borderColor, {
    double opacity = 1.0,
  }) {
    return Container(
      width: 32,
      height: 32,
      decoration: BoxDecoration(
        color: color.withValues(alpha: opacity),
        shape: BoxShape.circle,
        border: Border.all(
          color: borderColor,
          width: 2,
        ),
      ),
    );
  }
}

/// 功能亮点页
class _FeaturesPage extends StatelessWidget {
  const _FeaturesPage();

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    return Padding(
      padding: UIConstants.paddingLarge,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(
            l10n.onboardingFeaturesTitle,
            style: Theme.of(context).textTheme.headlineMedium?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
          ),
          const SizedBox(height: 32),
          _FeatureCard(
            icon: Icons.smart_toy,
            title: l10n.onboardingAiFeature,
            description: l10n.onboardingAiFeatureDescription,
          ),
          const SizedBox(height: 16),
          _FeatureCard(
            icon: Icons.replay,
            title: l10n.onboardingReplayFeature,
            description: l10n.onboardingReplayFeatureDescription,
          ),
          const SizedBox(height: 16),
          _FeatureCard(
            icon: Icons.palette,
            title: l10n.onboardingThemeFeature,
            description: l10n.onboardingThemeFeatureDescription,
          ),
          const SizedBox(height: 16),
          _FeatureCard(
            icon: Icons.bar_chart,
            title: l10n.onboardingStatisticsFeature,
            description: l10n.onboardingStatisticsFeatureDescription,
          ),
        ],
      ),
    );
  }
}

/// 信息卡片
class _InfoCard extends StatelessWidget {
  final IconData? icon;
  final Widget? customIcon;
  final String title;
  final String description;

  const _InfoCard({
    this.icon,
    this.customIcon,
    required this.title,
    required this.description,
  }) : assert(
          icon != null || customIcon != null,
          'Either icon or customIcon must be provided',
        );

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: scheme.surface,
        borderRadius: BorderRadius.circular(UIConstants.borderRadiusMedium),
        border: Border.all(color: scheme.outlineVariant),
      ),
      child: Row(
        children: [
          customIcon ?? Icon(icon!, size: 32, color: scheme.primary),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  title,
                  style: theme.textTheme.titleMedium,
                ),
                const SizedBox(height: 4),
                Text(
                  description,
                  style: theme.textTheme.bodyMedium?.copyWith(
                    color: scheme.onSurfaceVariant,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

/// 功能卡片
class _FeatureCard extends StatelessWidget {
  final IconData icon;
  final String title;
  final String description;
  const _FeatureCard({
    required this.icon,
    required this.title,
    required this.description,
  });

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final scheme = theme.colorScheme;
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: scheme.surface,
        borderRadius: BorderRadius.circular(UIConstants.borderRadiusMedium),
        border: Border.all(color: scheme.outlineVariant),
      ),
      child: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              color: scheme.secondaryContainer,
              borderRadius:
                  BorderRadius.circular(UIConstants.borderRadiusSmall),
            ),
            child: Icon(icon, size: 24, color: scheme.onSecondaryContainer),
          ),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  title,
                  style: theme.textTheme.titleMedium,
                ),
                const SizedBox(height: 4),
                Text(
                  description,
                  style: theme.textTheme.bodyMedium?.copyWith(
                    color: scheme.onSurfaceVariant,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

/// 方向箭头
class _DirectionArrow extends StatelessWidget {
  final IconData icon;

  const _DirectionArrow(this.icon);

  @override
  Widget build(BuildContext context) {
    return Icon(
      icon,
      size: 32,
      color: Theme.of(context).colorScheme.secondary,
    );
  }
}

/// 棋盘演示绘制器
class _BoardDemoPainter extends CustomPainter {
  const _BoardDemoPainter({required this.gridColor});

  final Color gridColor;

  @override
  void paint(Canvas canvas, Size size) {
    final cellSize = size.width / 4;

    // 绘制网格
    final gridPaint = Paint()
      ..color = gridColor
      ..strokeWidth = UIConstants.gridLineWidth
      ..style = PaintingStyle.stroke;

    for (var i = 0; i <= 4; i++) {
      // 横线
      canvas.drawLine(
        Offset(0, i * cellSize),
        Offset(size.width, i * cellSize),
        gridPaint,
      );
      // 竖线
      canvas.drawLine(
        Offset(i * cellSize, 0),
        Offset(i * cellSize, size.height),
        gridPaint,
      );
    }

    // 绘制初始棋子
    final positions = [
      // 黑方
      (0, 0, Colors.black),
      (1, 0, Colors.black),
      (2, 0, Colors.black),
      (3, 0, Colors.black),
      // 白方
      (0, 3, Colors.white),
      (1, 3, Colors.white),
      (2, 3, Colors.white),
      (3, 3, Colors.white),
    ];

    for (final (x, y, color) in positions) {
      final center = Offset(
        x * cellSize + cellSize / 2,
        y * cellSize + cellSize / 2,
      );
      final radius = cellSize * 0.3;

      final piecePaint = Paint()
        ..color = color
        ..style = PaintingStyle.fill;

      canvas.drawCircle(center, radius, piecePaint);

      final borderPaint = Paint()
        ..color = color == Colors.black ? Colors.white : Colors.black
        ..strokeWidth = 1.5
        ..style = PaintingStyle.stroke;

      canvas.drawCircle(center, radius, borderPaint);
    }
  }

  @override
  bool shouldRepaint(_BoardDemoPainter oldDelegate) =>
      oldDelegate.gridColor != gridColor;
}
