// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 为StorageService编写完整单元测试，覆盖设置、统计数据和游戏存档功能

/// StorageService 单元测试
///
/// 测试覆盖：
/// - 服务初始化
/// - 游戏设置保存/加载
/// - 统计数据保存/加载/更新
/// - 游戏存档保存/加载/删除
/// - 数据重置
library;

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:hive/hive.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:foursquare/meditation/meditation_session_persistence.dart';
import 'package:foursquare/models/board_state.dart';
import 'package:foursquare/models/game_record.dart';
import 'package:foursquare/models/game_result.dart';
import 'package:foursquare/models/game_save.dart';
import 'package:foursquare/models/move.dart';
import 'package:foursquare/models/piece_type.dart';
import 'package:foursquare/models/position.dart';
import 'package:foursquare/services/online_identity_service.dart';
import 'package:foursquare/services/storage_service.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  group('GameSettings模型', () {
    test('应该创建默认设置', () {
      const settings = GameSettings();

      expect(settings.soundEnabled, true);
      expect(settings.soundVolume, 0.7);
      expect(settings.musicEnabled, true);
      expect(settings.musicVolume, 0.5);
      expect(settings.musicTheme, 'main');
      expect(settings.vibrationEnabled, true);
      expect(settings.selectedTheme, 'default');
      expect(settings.difficulty, 'medium');
    });

    test('应该正确序列化和反序列化', () {
      const original = GameSettings(
        soundEnabled: false,
        soundVolume: 0.8,
        musicEnabled: false,
        musicVolume: 0.6,
        musicTheme: 'classic',
        vibrationEnabled: false,
        selectedTheme: 'dark',
        difficulty: 'hard',
      );

      final json = original.toJson();
      final restored = GameSettings.fromJson(json);

      expect(restored.soundEnabled, original.soundEnabled);
      expect(restored.soundVolume, original.soundVolume);
      expect(restored.musicEnabled, original.musicEnabled);
      expect(restored.musicVolume, original.musicVolume);
      expect(restored.musicTheme, original.musicTheme);
      expect(restored.vibrationEnabled, original.vibrationEnabled);
      expect(restored.selectedTheme, original.selectedTheme);
      expect(restored.difficulty, original.difficulty);
    });

    test('copyWith应该正确复制并修改属性', () {
      const original = GameSettings();

      final modified = original.copyWith(
        soundEnabled: false,
        difficulty: 'hard',
      );

      expect(modified.soundEnabled, false);
      expect(modified.difficulty, 'hard');
      expect(modified.soundVolume, original.soundVolume);
      expect(modified.musicEnabled, original.musicEnabled);
    });
  });

  group('GameStatistics模型', () {
    test('应该创建默认统计数据', () {
      const stats = GameStatistics();

      expect(stats.totalGames, 0);
      expect(stats.wins, 0);
      expect(stats.losses, 0);
      expect(stats.draws, 0);
      expect(stats.winStreak, 0);
      expect(stats.maxWinStreak, 0);
      expect(stats.totalMoves, 0);
      expect(stats.totalCaptures, 0);
      expect(stats.lastPlayedAt, null);
      expect(stats.difficultyWins, isEmpty);
      expect(stats.dailyWinRate, isEmpty);
      expect(stats.hourlyGames, isEmpty);
    });

    test('应该正确计算胜率', () {
      const stats = GameStatistics(
        totalGames: 10,
        wins: 7,
      );

      expect(stats.winRate, 0.7);
    });

    test('零场游戏时胜率应为0', () {
      const stats = GameStatistics();

      expect(stats.winRate, 0.0);
    });

    test('应该正确序列化和反序列化', () {
      final now = DateTime.now();
      final original = GameStatistics(
        totalGames: 20,
        wins: 15,
        losses: 3,
        draws: 2,
        winStreak: 5,
        maxWinStreak: 8,
        totalMoves: 300,
        totalCaptures: 50,
        lastPlayedAt: now,
        difficultyWins: {'easy': 5, 'medium': 8, 'hard': 2},
        dailyWinRate: {'2025-10-22': 0.75},
        hourlyGames: {'14': 10, '15': 10},
      );

      final json = original.toJson();
      final restored = GameStatistics.fromJson(json);

      expect(restored.totalGames, original.totalGames);
      expect(restored.wins, original.wins);
      expect(restored.losses, original.losses);
      expect(restored.draws, original.draws);
      expect(restored.winStreak, original.winStreak);
      expect(restored.maxWinStreak, original.maxWinStreak);
      expect(restored.totalMoves, original.totalMoves);
      expect(restored.totalCaptures, original.totalCaptures);
      expect(
        restored.lastPlayedAt?.toIso8601String(),
        original.lastPlayedAt?.toIso8601String(),
      );
      expect(restored.difficultyWins, original.difficultyWins);
    });

    test('copyWith应该正确复制并修改属性', () {
      const original = GameStatistics(totalGames: 5, wins: 3);

      final modified = original.copyWith(
        totalGames: 6,
        wins: 4,
      );

      expect(modified.totalGames, 6);
      expect(modified.wins, 4);
      expect(modified.losses, original.losses);
      expect(modified.draws, original.draws);
    });
  });

  group('StorageService', () {
    test('应该创建单例实例', () {
      final service1 = StorageService();
      final service2 = StorageService();

      expect(identical(service1, service2), true);
    });
  });

  group('完成对局幂等提交', () {
    late Directory temporaryDirectory;
    late Box<dynamic> statisticsBox;
    late StorageService storageService;

    setUp(() async {
      temporaryDirectory = await Directory.systemTemp.createTemp(
        'foursquare-storage-test-',
      );
      Hive.init(temporaryDirectory.path);
      statisticsBox = await Hive.openBox<dynamic>('statistics-test');
      storageService = StorageService.forTesting(
        statisticsBox: statisticsBox,
      );
    });

    tearDown(() async {
      await statisticsBox.close();
      await temporaryDirectory.delete(recursive: true);
    });

    test('同一gameId重复提交只新增一次历史和一次统计', () async {
      final record = _lanRecord('lan-game-1');

      expect(await storageService.recordCompletedGame(record), true);
      expect(await storageService.recordCompletedGame(record), true);

      final statistics = await storageService.loadStatistics();
      final history = await storageService.loadGameHistory();
      expect(statistics.totalGames, 1);
      expect(statistics.wins, 1);
      expect(statistics.losses, 0);
      expect(history.map((item) => item.id), ['lan-game-1']);
    });

    test('并发提交不会重复统计同一gameId或丢失其他对局', () async {
      final first = _lanRecord('lan-game-1');
      final second = _lanRecord('lan-game-2');

      final results = await Future.wait([
        storageService.recordCompletedGame(first),
        storageService.recordCompletedGame(first),
        storageService.recordCompletedGame(second),
      ]);

      expect(results, everyElement(true));
      final statistics = await storageService.loadStatistics();
      final history = await storageService.loadGameHistory();
      expect(statistics.totalGames, 2);
      expect(statistics.wins, 2);
      expect(history.map((item) => item.id).toSet(), {
        'lan-game-1',
        'lan-game-2',
      });
    });
  });

  group('游戏存档可用性', () {
    late Directory temporaryDirectory;
    late Box<dynamic> gameSaveBox;
    late StorageService storageService;

    setUp(() async {
      temporaryDirectory = await Directory.systemTemp.createTemp(
        'foursquare-game-save-test-',
      );
      Hive.init(temporaryDirectory.path);
      gameSaveBox = await Hive.openBox<dynamic>('game-save-validity-test');
      storageService = StorageService.forTesting(gameSaveBox: gameSaveBox);
    });

    tearDown(() async {
      if (gameSaveBox.isOpen) {
        await gameSaveBox.close();
      }
      await temporaryDirectory.delete(recursive: true);
    });

    test('损坏存档不显示继续游戏且不会被自动删除', () async {
      await gameSaveBox.put('current_game_save', <String, dynamic>{
        'schemaVersion': 2,
        'id': 42,
      });

      expect(await storageService.loadGame(), isNull);
      expect(await storageService.hasSavedGame(), isFalse);
      expect(gameSaveBox.containsKey('current_game_save'), isTrue);
    });

    test('Hive重新打开后完整恢复进行中存档', () async {
      final move = Move(
        from: const Position(0, 0),
        to: const Position(0, 1),
        player: PieceType.black,
        capturedPieces: const [Position(2, 3), Position(3, 3)],
        timestamp: DateTime.utc(2026, 8, 24, 10),
      );
      final save = GameSave(
        id: 'reopen-save',
        matchId: 'reopen-match',
        saveTime: DateTime.utc(2026, 8, 24, 10, 1),
        startedAt: DateTime.utc(2026, 8, 24, 9, 58),
        boardState: BoardStateData.fromBoardState(
          BoardState.initial(currentPlayer: PieceType.white),
        ),
        moveHistory: [MoveData.fromMove(move)],
        currentPlayer: 'white',
        startingPlayer: 'black',
        humanPlayer: 'black',
        noCapturePlyCount: 19,
        turnRemainingMilliseconds: 41000,
        mode: 'pve',
        aiDifficulty: 'medium',
      );

      expect(await storageService.saveGame(save), isTrue);
      await gameSaveBox.close();
      gameSaveBox = await Hive.openBox<dynamic>('game-save-validity-test');
      storageService = StorageService.forTesting(gameSaveBox: gameSaveBox);

      final restored = await storageService.loadGame();
      expect(restored, isNotNull);
      expect(restored!.matchId, 'reopen-match');
      expect(restored.currentPlayer, 'white');
      expect(restored.startingPlayer, 'black');
      expect(restored.humanPlayer, 'black');
      expect(restored.noCapturePlyCount, 19);
      expect(restored.turnRemainingMilliseconds, 41000);
      expect(restored.moveHistory.single.capturedPositions, hasLength(2));
    });
  });

  group('冥想存档所有权', () {
    late Directory temporaryDirectory;
    late Box<dynamic> statisticsBox;
    late Box<dynamic> gameSaveBox;
    late Box<dynamic> meditationBox;
    late StorageService storageService;

    setUp(() async {
      temporaryDirectory = await Directory.systemTemp.createTemp(
        'foursquare-meditation-storage-test-',
      );
      Hive.init(temporaryDirectory.path);
      statisticsBox = await Hive.openBox<dynamic>('statistics-reset-test');
      gameSaveBox = await Hive.openBox<dynamic>('game-save-reset-test');
      meditationBox =
          await Hive.openBox<dynamic>('meditation-session-reset-test');
      SharedPreferences.setMockInitialValues({
        'test': true,
        OnlineIdentityService.storageKey: 'device-existing',
      });
      storageService = StorageService.forTesting(
        statisticsBox: statisticsBox,
        gameSaveBox: gameSaveBox,
        meditationSessionBox: meditationBox,
        preferences: await SharedPreferences.getInstance(),
      );
    });

    tearDown(() async {
      if (statisticsBox.isOpen) await statisticsBox.close();
      if (gameSaveBox.isOpen) await gameSaveBox.close();
      if (meditationBox.isOpen) await meditationBox.close();
      await temporaryDirectory.delete(recursive: true);
    });

    test('全部重置清理本地数据并保留在线身份', () async {
      await statisticsBox.put('value', 1);
      await gameSaveBox.put('value', 1);
      await meditationBox.put('value', 1);

      expect(await storageService.resetAll(), true);

      expect(statisticsBox.isEmpty, true);
      expect(gameSaveBox.isEmpty, true);
      expect(meditationBox.isEmpty, true);
      final preferences = await SharedPreferences.getInstance();
      expect(preferences.getBool('test'), isNull);
      expect(
        preferences.getString(OnlineIdentityService.storageKey),
        'device-existing',
      );
    });

    test('只能从已初始化的应用存储创建冥想仓库', () async {
      expect(
        storageService.createMeditationSessionRepository(),
        isA<HiveMeditationSessionRepository>(),
      );
      expect(
        StorageService.forTesting().createMeditationSessionRepository,
        throwsStateError,
      );
    });

    test('销毁应用存储会关闭冥想 Box', () async {
      await storageService.dispose();

      expect(statisticsBox.isOpen, false);
      expect(gameSaveBox.isOpen, false);
      expect(meditationBox.isOpen, false);
    });
  });
}

GameRecord _lanRecord(String id) {
  return GameRecord(
    id: id,
    completedAt: DateTime.utc(2026, 8, 1, 12),
    mode: 'lan',
    startingPlayer: PieceType.black,
    humanPlayer: PieceType.black,
    result: GameResult.blackWin(
      reason: '白方只剩一枚棋子',
      moveCount: 12,
      duration: const Duration(minutes: 3),
    ),
    moves: const [],
  );
}
