// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 实现游戏保存数据模型，支持游戏状态的序列化和反序列化

/// Game Save - 游戏存档模型
///
/// 职责：
/// - 保存完整的游戏状态
/// - 支持JSON序列化/反序列化
/// - 用于游戏中途退出后继续
library;

import 'package:equatable/equatable.dart';
import '../bloc/game_event.dart';
import 'board_state.dart';
import 'move.dart';
import 'position.dart';
import 'piece_type.dart';

/// 游戏存档数据模型
class GameSave extends Equatable {
  /// 存档结构版本；正式规则模型从 v2 开始。
  final int schemaVersion;
  final String id;
  final DateTime saveTime;
  final String? matchId;
  final DateTime? startedAt;
  final BoardStateData boardState;
  final List<MoveData> moveHistory;
  final String currentPlayer; // 'black' or 'white'
  final String startingPlayer; // 'black' or 'white'
  final String? humanPlayer; // AI mode only
  final int noCapturePlyCount;
  final int turnRemainingMilliseconds;
  final String mode; // 'pvp' or 'pve'
  final String? aiDifficulty; // 'easy', 'medium', 'hard'

  const GameSave({
    this.schemaVersion = 2,
    required this.id,
    required this.saveTime,
    this.matchId,
    this.startedAt,
    required this.boardState,
    required this.moveHistory,
    required this.currentPlayer,
    this.startingPlayer = 'black',
    this.humanPlayer,
    this.noCapturePlyCount = 0,
    this.turnRemainingMilliseconds = 60000,
    required this.mode,
    this.aiDifficulty,
  });

  Map<String, dynamic> toJson() => {
        'schemaVersion': schemaVersion,
        'id': id,
        'saveTime': saveTime.toIso8601String(),
        'matchId': matchId,
        'startedAt': startedAt?.toUtc().toIso8601String(),
        'boardState': boardState.toJson(),
        'moveHistory': moveHistory.map((m) => m.toJson()).toList(),
        'currentPlayer': currentPlayer,
        'startingPlayer': startingPlayer,
        'humanPlayer': humanPlayer,
        'noCapturePlyCount': noCapturePlyCount,
        'turnRemainingMilliseconds': turnRemainingMilliseconds,
        'mode': mode,
        'aiDifficulty': aiDifficulty,
      };

  factory GameSave.fromJson(Map<String, dynamic> json) {
    final version = json['schemaVersion'] as int? ?? 1;
    if (version != 1 && version != 2) {
      throw const FormatException('Unsupported game save version');
    }
    const players = ['black', 'white'];
    final count = json['noCapturePlyCount'] as int? ?? 0;
    final remaining = json['turnRemainingMilliseconds'] as int? ?? 60000;
    if (!players.contains(json['currentPlayer']) ||
        !players.contains(json['startingPlayer'] ?? 'black') ||
        (json['humanPlayer'] != null &&
            !players.contains(json['humanPlayer'])) ||
        !const ['pvp', 'pve', 'online'].contains(json['mode']) ||
        (json['aiDifficulty'] != null &&
            !const ['easy', 'medium', 'hard'].contains(json['aiDifficulty'])) ||
        count < 0 ||
        count > 50 ||
        remaining < 0 ||
        remaining > 60000) {
      throw const FormatException('Invalid game save state');
    }
    return GameSave(
      schemaVersion: version,
      id: json['id'] as String,
      saveTime: DateTime.parse(json['saveTime'] as String),
      matchId: json['matchId'] as String?,
      startedAt: json['startedAt'] == null
          ? null
          : DateTime.parse(json['startedAt'] as String).toUtc(),
      boardState: BoardStateData.fromJson(
        Map<String, dynamic>.from(json['boardState']),
      ),
      moveHistory: (json['moveHistory'] as List)
          .map((m) => MoveData.fromJson(Map<String, dynamic>.from(m)))
          .toList(),
      currentPlayer: json['currentPlayer'] as String,
      startingPlayer: json['startingPlayer'] as String? ?? 'black',
      humanPlayer: json['humanPlayer'] as String?,
      noCapturePlyCount: json['noCapturePlyCount'] as int? ?? 0,
      turnRemainingMilliseconds:
          json['turnRemainingMilliseconds'] as int? ?? 60000,
      mode: json['mode'] as String,
      aiDifficulty: json['aiDifficulty'] as String?,
    );
  }

  @override
  List<Object?> get props => [
        id,
        schemaVersion,
        saveTime,
        matchId,
        startedAt,
        boardState,
        moveHistory,
        currentPlayer,
        startingPlayer,
        humanPlayer,
        noCapturePlyCount,
        turnRemainingMilliseconds,
        mode,
        aiDifficulty,
      ];
}

/// 棋盘状态数据（可序列化）
class BoardStateData extends Equatable {
  final List<List<String>> grid; // 'black', 'white', 'empty'
  final List<PositionData> blackPieces;
  final List<PositionData> whitePieces;

  const BoardStateData({
    required this.grid,
    required this.blackPieces,
    required this.whitePieces,
  });

  Map<String, dynamic> toJson() => {
        'grid': grid,
        'blackPieces': blackPieces.map((p) => p.toJson()).toList(),
        'whitePieces': whitePieces.map((p) => p.toJson()).toList(),
      };

  factory BoardStateData.fromJson(Map<String, dynamic> json) {
    final grid = json['grid'] as List;
    if (grid.length != 4 ||
        grid.any((row) => row is! List || row.length != 4)) {
      throw const FormatException(
        'Game save board must have four rows and columns',
      );
    }
    if (grid
        .expand((row) => row as List)
        .any((cell) => !const ['black', 'white', 'empty'].contains(cell))) {
      throw const FormatException('Unknown game save board piece');
    }
    final data = BoardStateData(
      grid: (json['grid'] as List)
          .map((row) => (row as List).map((cell) => cell as String).toList())
          .toList(),
      blackPieces: (json['blackPieces'] as List)
          .map((p) => PositionData.fromJson(Map<String, dynamic>.from(p)))
          .toList(),
      whitePieces: (json['whitePieces'] as List)
          .map((p) => PositionData.fromJson(Map<String, dynamic>.from(p)))
          .toList(),
    );
    final occupied = <String>{};
    for (final pieces in [
      (data.blackPieces, 'black'),
      (data.whitePieces, 'white'),
    ]) {
      if (pieces.$1.length > 4) {
        throw const FormatException('Too many saved pieces');
      }
      for (final position in pieces.$1) {
        if (data.grid[position.y][position.x] != pieces.$2 ||
            !occupied.add('${position.x},${position.y}')) {
          throw const FormatException('Saved piece list does not match board');
        }
      }
    }
    if (occupied.length !=
        data.grid
            .expand((row) => row)
            .where((cell) => cell != 'empty')
            .length) {
      throw const FormatException('Saved piece list is incomplete');
    }
    return data;
  }

  factory BoardStateData.fromBoardState(BoardState state) {
    return BoardStateData(
      grid: state.grid
          .map((row) => row.map((piece) => _pieceTypeToString(piece)).toList())
          .toList(),
      blackPieces:
          state.blackPieces.map((p) => PositionData.fromPosition(p)).toList(),
      whitePieces:
          state.whitePieces.map((p) => PositionData.fromPosition(p)).toList(),
    );
  }

  BoardState toBoardState(PieceType currentPlayer) {
    return BoardState(
      grid: grid
          .map((row) => row.map((cell) => _stringToPieceType(cell)).toList())
          .toList(),
      blackPieces: blackPieces.map((p) => p.toPosition()).toList(),
      whitePieces: whitePieces.map((p) => p.toPosition()).toList(),
      currentPlayer: currentPlayer,
    );
  }

  static String _pieceTypeToString(PieceType type) {
    switch (type) {
      case PieceType.black:
        return 'black';
      case PieceType.white:
        return 'white';
      case PieceType.empty:
        return 'empty';
    }
  }

  static PieceType _stringToPieceType(String str) {
    switch (str) {
      case 'black':
        return PieceType.black;
      case 'white':
        return PieceType.white;
      default:
        return PieceType.empty;
    }
  }

  @override
  List<Object?> get props => [grid, blackPieces, whitePieces];
}

/// 位置数据（可序列化）
class PositionData extends Equatable {
  final int x;
  final int y;

  const PositionData({
    required this.x,
    required this.y,
  });

  Map<String, dynamic> toJson() => {
        'x': x,
        'y': y,
      };

  factory PositionData.fromJson(Map<String, dynamic> json) {
    final x = json['x'] as int;
    final y = json['y'] as int;
    if (x < 0 || x > 3 || y < 0 || y > 3) {
      throw const FormatException('Saved position is outside the board');
    }
    return PositionData(
      x: x,
      y: y,
    );
  }

  factory PositionData.fromPosition(Position pos) {
    return PositionData(x: pos.x, y: pos.y);
  }

  Position toPosition() {
    return Position(x, y);
  }

  @override
  List<Object?> get props => [x, y];
}

/// 移动数据（可序列化）
class MoveData extends Equatable {
  final PositionData from;
  final PositionData to;
  final List<PositionData> capturedPositions;
  final String player;
  final DateTime timestamp;

  /// 兼容旧存档的第一个被吃位置。
  PositionData? get capturedPosition =>
      capturedPositions.isEmpty ? null : capturedPositions.first;

  /// 兼容旧存档中实际表示移动方的错误字段名。
  String get capturedPiece => player;

  MoveData({
    required this.from,
    required this.to,
    List<PositionData> capturedPositions = const [],
    PositionData? capturedPosition,
    String? player,
    String? capturedPiece,
    DateTime? timestamp,
  })  : capturedPositions = List.unmodifiable(
          capturedPosition == null
              ? capturedPositions
              : <PositionData>[
                  ...capturedPositions,
                  if (!capturedPositions.contains(capturedPosition))
                    capturedPosition,
                ],
        ),
        player = player ?? capturedPiece ?? 'black',
        timestamp = timestamp ?? DateTime.fromMillisecondsSinceEpoch(0);

  Map<String, dynamic> toJson() => {
        'from': from.toJson(),
        'to': to.toJson(),
        'capturedPositions':
            capturedPositions.map((position) => position.toJson()).toList(),
        'player': player,
        'timestamp': timestamp.toIso8601String(),
        // 旧版本兼容字段。
        'capturedPosition': capturedPosition?.toJson(),
        'capturedPiece': capturedPiece,
      };

  factory MoveData.fromJson(Map<String, dynamic> json) {
    final capturedPositionsJson = json['capturedPositions'] as List<dynamic>?;
    final legacyCapturedPosition = json['capturedPosition'] != null
        ? PositionData.fromJson(
            Map<String, dynamic>.from(json['capturedPosition']),
          )
        : null;
    return MoveData(
      from: PositionData.fromJson(Map<String, dynamic>.from(json['from'])),
      to: PositionData.fromJson(Map<String, dynamic>.from(json['to'])),
      capturedPositions: capturedPositionsJson
              ?.map(
                (position) => PositionData.fromJson(
                  Map<String, dynamic>.from(position),
                ),
              )
              .toList(growable: false) ??
          const [],
      capturedPosition:
          capturedPositionsJson == null ? legacyCapturedPosition : null,
      player: json['player'] as String?,
      capturedPiece: json['capturedPiece'] as String?,
      timestamp: json['timestamp'] == null
          ? null
          : DateTime.parse(json['timestamp'] as String),
    );
  }

  factory MoveData.fromMove(Move move) {
    return MoveData(
      from: PositionData.fromPosition(move.from),
      to: PositionData.fromPosition(move.to),
      capturedPositions: move.capturedPieces
          .map(PositionData.fromPosition)
          .toList(growable: false),
      player: BoardStateData._pieceTypeToString(move.player),
      timestamp: move.timestamp,
    );
  }

  Move toMove() {
    return Move(
      from: from.toPosition(),
      to: to.toPosition(),
      player: BoardStateData._stringToPieceType(player),
      capturedPieces:
          capturedPositions.map((position) => position.toPosition()).toList(),
      timestamp: timestamp,
    );
  }

  @override
  List<Object?> get props => [from, to, capturedPositions, player, timestamp];
}

/// 游戏模式转换扩展
extension GameModeExtensions on GameMode {
  String toJson() {
    switch (this) {
      case GameMode.pvp:
        return 'pvp';
      case GameMode.pve:
        return 'pve';
      case GameMode.online:
        return 'online';
    }
  }

  static GameMode fromJson(String json) {
    switch (json) {
      case 'pvp':
        return GameMode.pvp;
      case 'pve':
        return GameMode.pve;
      case 'online':
        return GameMode.online;
      default:
        return GameMode.pvp;
    }
  }
}
