// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 实现移动记录模型，记录游戏中的每次移动操作

import 'package:equatable/equatable.dart';
import 'position.dart';
import 'piece_type.dart';

/// 移动记录
///
/// 记录一次移动操作的完整信息，包括：
/// - 起始位置
/// - 目标位置
/// - 移动方
/// - 被吃棋子位置（横向后纵向，最多两个）
/// - 移动时间
class Move extends Equatable {
  /// 起始位置
  final Position from;

  /// 目标位置
  final Position to;

  /// 移动方
  final PieceType player;

  /// 被吃棋子位置，顺序固定为横向后纵向。
  final List<Position> capturedPieces;

  /// 兼容旧调用方和旧协议的首个被吃棋子。
  Position? get capturedPiece =>
      capturedPieces.isEmpty ? null : capturedPieces.first;

  /// 移动时间
  final DateTime timestamp;

  Move({
    required this.from,
    required this.to,
    required this.player,
    List<Position> capturedPieces = const [],
    Position? capturedPiece,
    required this.timestamp,
  }) : capturedPieces = List.unmodifiable(
          capturedPiece == null
              ? capturedPieces
              : <Position>[
                  ...capturedPieces,
                  if (!capturedPieces.contains(capturedPiece)) capturedPiece,
                ],
        );

  /// 创建移动记录（使用当前时间）
  factory Move.now({
    required Position from,
    required Position to,
    required PieceType player,
    List<Position> capturedPieces = const [],
    Position? capturedPiece,
  }) {
    return Move(
      from: from,
      to: to,
      player: player,
      capturedPieces: capturedPieces,
      capturedPiece: capturedPiece,
      timestamp: DateTime.now(),
    );
  }

  /// 是否有吃子
  bool get hasCapture => capturedPieces.isNotEmpty;

  /// 本次落子吃掉的棋子数量。
  int get captureCount => capturedPieces.length;

  /// 创建副本
  Move copyWith({
    Position? from,
    Position? to,
    PieceType? player,
    List<Position>? capturedPieces,
    Position? capturedPiece,
    bool clearCapturedPieces = false,
    DateTime? timestamp,
  }) {
    return Move(
      from: from ?? this.from,
      to: to ?? this.to,
      player: player ?? this.player,
      capturedPieces: clearCapturedPieces
          ? const []
          : capturedPieces ?? this.capturedPieces,
      capturedPiece: capturedPiece,
      timestamp: timestamp ?? this.timestamp,
    );
  }

  /// 转换为Map（用于序列化）
  Map<String, dynamic> toJson() {
    return {
      'from': {'x': from.x, 'y': from.y},
      'to': {'x': to.x, 'y': to.y},
      'player': player.name,
      'capturedPieces': capturedPieces
          .map((position) => {'x': position.x, 'y': position.y})
          .toList(growable: false),
      // 暂时保留单值字段，供旧版本客户端读取。
      'capturedPiece': capturedPiece != null
          ? {'x': capturedPiece!.x, 'y': capturedPiece!.y}
          : null,
      'timestamp': timestamp.toIso8601String(),
    };
  }

  /// 从Map创建（用于反序列化）
  factory Move.fromJson(Map<String, dynamic> json) {
    final fromMap = Map<String, dynamic>.from(json['from'] as Map);
    final toMap = Map<String, dynamic>.from(json['to'] as Map);
    final capturedList = json['capturedPieces'] as List<dynamic>?;
    final capturedMap = json['capturedPiece'] == null
        ? null
        : Map<String, dynamic>.from(json['capturedPiece'] as Map);
    final capturedPieces = capturedList != null
        ? capturedList.map(
            (item) {
              final map = Map<String, dynamic>.from(item as Map);
              return Position(map['x'] as int, map['y'] as int);
            },
          ).toList(growable: false)
        : <Position>[
            if (capturedMap != null)
              Position(
                capturedMap['x'] as int,
                capturedMap['y'] as int,
              ),
          ];

    return Move(
      from: Position(fromMap['x'] as int, fromMap['y'] as int),
      to: Position(toMap['x'] as int, toMap['y'] as int),
      player: PieceType.values.firstWhere(
        (e) => e.name == json['player'],
      ),
      capturedPieces: capturedPieces,
      timestamp: DateTime.parse(json['timestamp'] as String),
    );
  }

  /// 获取移动描述（用于显示）
  String getDescription() {
    final buffer = StringBuffer();
    buffer.write('${player.getDisplayName()}从');
    buffer.write('(${from.x},${from.y})移至(${to.x},${to.y})');
    if (hasCapture) {
      final positions = capturedPieces
          .map((position) => '(${position.x},${position.y})')
          .join('、');
      buffer.write('，吃掉$positions');
    }
    return buffer.toString();
  }

  @override
  List<Object?> get props => [from, to, player, capturedPieces, timestamp];

  @override
  String toString() {
    return 'Move(from: $from, to: $to, player: $player, '
        'captured: $capturedPieces, time: $timestamp)';
  }
}
