// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 主程序入口，启动游戏应用

import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'ui/screens/home_page.dart';
import 'ui/screens/onboarding_page.dart';
import 'services/storage_service.dart';
import 'services/app_locale_controller.dart';
import 'services/audio_coordinator.dart';
import 'services/performance_monitor.dart';
import 'services/diagnostics_service.dart';
import 'theme/theme_manager.dart';
import 'theme/theme_pack_registry.dart';
import 'l10n/app_localizations.dart';
import 'constants/storage_constants.dart';

import 'package:flutter/foundation.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 初始化存储服务
  final storageService = StorageService();
  await storageService.initialize();

  // 加载环境变量
  const envName = String.fromEnvironment('ENV');
  final String envFile;
  if (envName.isNotEmpty) {
    envFile = '.env.$envName';
  } else {
    envFile = kReleaseMode ? ".env.production" : ".env.development";
  }

  await dotenv.load(fileName: envFile);

  await ThemeManager().initialize();
  await AudioCoordinator().initialize();
  final settings = await storageService.loadSettings();
  PerformanceMonitor().setEnabled(settings.performanceMonitoringEnabled);

  await DiagnosticsService().run(
    enabled: settings.performanceMonitoringEnabled,
    dsn: dotenv.maybeGet('SENTRY_DSN'),
    environment: kReleaseMode ? 'production' : 'development',
    appRunner: () => runApp(const FourSquareGameApp()),
  );
}

class FourSquareGameApp extends StatefulWidget {
  const FourSquareGameApp({super.key});

  @override
  State<FourSquareGameApp> createState() => _FourSquareGameAppState();
}

class _FourSquareGameAppState extends State<FourSquareGameApp>
    with WidgetsBindingObserver {
  final StorageService _storageService = StorageService();
  final ThemePackRegistry _themeRegistry = ThemePackRegistry.phaseOne();
  final AppLocaleController _localeController = AppLocaleController();
  late ThemeData _currentTheme = _themeRegistry.defaultPack.themeData;
  bool _isLoading = true;
  bool _isFirstLaunch = true;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _initialize();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      AudioCoordinator().resumeAll();
    } else {
      AudioCoordinator().pauseAll();
    }
  }

  Future<void> _initialize() async {
    final settings = await _storageService.loadSettings();
    final selectedTheme = _themeRegistry.resolve(settings.selectedTheme);
    final prefs = await SharedPreferences.getInstance();
    final isFirstLaunch =
        prefs.getBool(StorageConstants.keyFirstLaunch) ?? true;
    if (!mounted) {
      return;
    }

    _localeController.select(settings.localeCode);
    setState(() {
      _currentTheme = selectedTheme.themeData;
      _isFirstLaunch = isFirstLaunch;
      _isLoading = false;
    });
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _localeController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return const MaterialApp(
        home: Scaffold(
          body: Center(
            child: CircularProgressIndicator(),
          ),
        ),
        debugShowCheckedModeBanner: false,
      );
    }

    return AppLocaleScope(
      controller: _localeController,
      child: ValueListenableBuilder<Locale>(
        valueListenable: _localeController,
        builder: (context, locale, child) {
          return MaterialApp(
            onGenerateTitle: (context) =>
                AppLocalizations.of(context)?.appTitle ?? '四子游戏',
            locale: locale,
            theme: _currentTheme,
            home: _isFirstLaunch ? const OnboardingPage() : const HomePage(),
            routes: {
              '/home': (context) => const HomePage(),
              '/onboarding': (context) => const OnboardingPage(),
            },
            debugShowCheckedModeBanner: false,
            localizationsDelegates: const [
              AppLocalizations.delegate,
              GlobalMaterialLocalizations.delegate,
              GlobalWidgetsLocalizations.delegate,
              GlobalCupertinoLocalizations.delegate,
            ],
            supportedLocales: AppLocaleController.supportedLocales,
          );
        },
      ),
    );
  }
}
