// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 实现带动画效果的棋盘Widget，支持棋子移动动画和吃子动画

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../../models/board_state.dart';
import '../../models/position.dart';
import '../../models/piece_type.dart';
import '../../constants/ui_constants.dart';
import '../../constants/game_constants.dart';
import '../../models/board_theme.dart';
import 'board_painter.dart';
import 'dart:math' as math;

/// 带动画效果的棋盘Widget
///
/// 支持：
/// - 棋子移动动画（300ms平滑过渡）
/// - 吃子动画（缩放消失效果）
/// - 震动反馈
class AnimatedBoardWidget extends StatefulWidget {
  final BoardState boardState;
  final Position? selectedPiece;
  final List<Position> validMoves;
  final Position? lastMoveFrom;
  final Position? lastMoveTo;
  final List<Position> capturedPiecePositions;
  final Function(Position) onPositionTapped;
  final double? size;
  final bool vibrationEnabled;
  final bool animationEnabled;
  final bool particleEnabled;
  final bool flipBoard;
  final BoardTheme? theme; // 棋盘主题

  const AnimatedBoardWidget({
    super.key,
    required this.boardState,
    required this.onPositionTapped,
    this.selectedPiece,
    this.validMoves = const [],
    this.lastMoveFrom,
    this.lastMoveTo,
    this.capturedPiecePositions = const [],
    this.size,
    this.vibrationEnabled = true,
    this.animationEnabled = true,
    this.particleEnabled = true,
    this.flipBoard = false,
    this.theme,
  });

  @override
  State<AnimatedBoardWidget> createState() => _AnimatedBoardWidgetState();
}

class _AnimatedBoardWidgetState extends State<AnimatedBoardWidget>
    with TickerProviderStateMixin {
  // 移动动画控制器
  AnimationController? _moveAnimationController;
  Animation<Offset>? _moveAnimation;
  Position? _animatingTo;
  PieceType? _animatingPiece;

  // 吃子动画控制器
  AnimationController? _captureAnimationController;
  Animation<double>? _captureScaleAnimation;
  Animation<double>? _captureOpacityAnimation;
  Map<Position, PieceType> _capturingPieces = const {};
  int _captureGeneration = 0;

  // 选中呼吸动画控制器
  AnimationController? _selectionAnimationController;
  Animation<double>? _selectionPulseAnimation;

  @override
  void initState() {
    super.initState();
    _initAnimations();
  }

  @override
  void dispose() {
    _moveAnimationController?.dispose();
    _captureAnimationController?.dispose();
    _selectionAnimationController?.dispose();
    super.dispose();
  }

  void _initAnimations() {
    // 移动动画：300ms，使用easeOutBack曲线实现微弹效果
    _moveAnimationController = AnimationController(
      duration: const Duration(milliseconds: 300),
      vsync: this,
    );

    // 吃子动画：400ms，加入旋转效果
    _captureAnimationController = AnimationController(
      duration: const Duration(milliseconds: 400),
      vsync: this,
    );

    _captureScaleAnimation = TweenSequence<double>([
      TweenSequenceItem(
        tween: Tween<double>(begin: 1.0, end: 1.2)
            .chain(CurveTween(curve: Curves.easeOut)),
        weight: 25,
      ),
      TweenSequenceItem(
        tween: Tween<double>(begin: 1.2, end: 0.0)
            .chain(CurveTween(curve: Curves.easeIn)),
        weight: 75,
      ),
    ]).animate(_captureAnimationController!);

    _captureOpacityAnimation = Tween<double>(
      begin: 1.0,
      end: 0.0,
    ).animate(
      CurvedAnimation(
        parent: _captureAnimationController!,
        curve: const Interval(0.25, 1.0, curve: Curves.easeOut),
      ),
    );

    // 选中呼吸动画：1.5s循环
    _selectionAnimationController = AnimationController(
      duration: const Duration(milliseconds: 1500),
      vsync: this,
    );

    _selectionPulseAnimation = Tween<double>(
      begin: 1.0,
      end: 1.15,
    ).animate(
      CurvedAnimation(
        parent: _selectionAnimationController!,
        curve: Curves.easeInOut,
      ),
    );
    _syncSelectionPulse();
  }

  void _syncSelectionPulse() {
    final controller = _selectionAnimationController;
    if (controller == null) return;
    if (widget.animationEnabled && widget.selectedPiece != null) {
      if (!controller.isAnimating) controller.repeat(reverse: true);
    } else {
      controller.stop();
      if (controller.value != 0) controller.reset();
    }
  }

  @override
  void didUpdateWidget(AnimatedBoardWidget oldWidget) {
    super.didUpdateWidget(oldWidget);

    final lastMoveChanged = widget.lastMoveFrom != oldWidget.lastMoveFrom ||
        widget.lastMoveTo != oldWidget.lastMoveTo;
    _syncSelectionPulse();

    if (oldWidget.animationEnabled != widget.animationEnabled) {
      if (!widget.animationEnabled) {
        _moveAnimationController?.stop();
        _captureAnimationController?.stop();
        _captureGeneration++;
        setState(() {
          _animatingTo = null;
          _animatingPiece = null;
          _capturingPieces = const {};
        });
      }
    }

    if (!widget.animationEnabled) {
      return;
    }

    // 检测棋盘状态变化，如果正在动画的位置棋子变化了，清除动画状态
    if (_animatingTo != null && widget.boardState != oldWidget.boardState) {
      final currentPiece = widget.boardState.getPiece(_animatingTo!);
      // 如果目标位置的棋子与动画棋子不同，说明棋盘状态变化了（如撤销）
      if (currentPiece != _animatingPiece) {
        setState(() {
          _animatingTo = null;
          _animatingPiece = null;
        });
        _moveAnimationController?.stop();
        return;
      }
    }

    // 检测移动
    if (widget.lastMoveFrom != null &&
        widget.lastMoveTo != null &&
        lastMoveChanged) {
      _playMoveAnimation(
        widget.lastMoveFrom!,
        widget.lastMoveTo!,
        widget.boardState.getPiece(widget.lastMoveTo!),
      );
    } else if (lastMoveChanged) {
      // lastMove变化但为空（如撤销到初始状态），清除动画状态
      setState(() {
        _animatingTo = null;
        _animatingPiece = null;
      });
    }

    // 检测吃子
    if (lastMoveChanged ||
        !listEquals(
          widget.capturedPiecePositions,
          oldWidget.capturedPiecePositions,
        )) {
      if (widget.capturedPiecePositions.isEmpty) {
        _captureGeneration++;
        _captureAnimationController?.stop();
        _captureAnimationController?.reset();
        setState(() => _capturingPieces = const {});
      } else {
        _playCaptureAnimation(
          widget.capturedPiecePositions,
          oldWidget.boardState,
        );
      }
    }
  }

  /// 播放移动动画
  void _playMoveAnimation(Position from, Position to, PieceType? piece) {
    if (!widget.animationEnabled) return;
    if (piece == null) return;

    setState(() {
      _animatingTo = to;
      _animatingPiece = piece;
    });

    _moveAnimation = Tween<Offset>(
      begin: Offset(from.x.toDouble(), from.y.toDouble()),
      end: Offset(to.x.toDouble(), to.y.toDouble()),
    ).animate(
      CurvedAnimation(
        parent: _moveAnimationController!,
        curve: Curves.easeOutBack, // 使用easeOutBack实现微弹效果
      ),
    );

    _moveAnimationController!.forward(from: 0.0).then((_) {
      // 确保动画完成后立即显示棋子
      if (mounted) {
        setState(() {
          _animatingTo = null;
          _animatingPiece = null;
        });
      }
    });
  }

  /// 播放吃子动画
  void _playCaptureAnimation(
    List<Position> positions,
    BoardState previousBoard,
  ) {
    if (!widget.animationEnabled) return;

    final pieces = <Position, PieceType>{};
    for (final position in positions) {
      final piece = previousBoard.getPiece(position);
      if (piece != PieceType.empty) {
        pieces[position] = piece;
      }
    }
    if (pieces.isEmpty) return;

    final generation = ++_captureGeneration;

    setState(() {
      _capturingPieces = Map.unmodifiable(pieces);
    });

    // 震动反馈
    if (widget.vibrationEnabled) {
      HapticFeedback.mediumImpact();
    }

    _captureAnimationController!.forward(from: 0.0).then((_) {
      if (!mounted || generation != _captureGeneration) return;
      setState(() => _capturingPieces = const {});
      _captureAnimationController!.reset();
    });
  }

  @override
  Widget build(BuildContext context) {
    final boardSize = widget.size ?? _calculateBoardSize(context);
    final cellSize = boardSize / GameConstants.boardSize;

    Widget boardStack = SizedBox(
      width: boardSize,
      height: boardSize,
      child: Stack(
        children: [
          // Base board and static pieces
          RepaintBoundary(
            child: _buildBasicBoard(boardSize),
          ),

          // Moving piece
          if (widget.animationEnabled &&
              _animatingPiece != null &&
              _moveAnimation != null)
            _buildAnimatingPiece(cellSize),

          // Captured piece
          if (widget.animationEnabled)
            ..._capturingPieces.entries.map(
              (capture) => _buildCapturingPiece(
                cellSize,
                capture.key,
                capture.value,
              ),
            ),

          if (widget.animationEnabled &&
              widget.particleEnabled &&
              _capturingPieces.isNotEmpty)
            ..._capturingPieces.entries.map(
              (capture) => RepaintBoundary(
                child: _buildCaptureParticles(
                  boardSize,
                  cellSize,
                  capture.key,
                  capture.value,
                ),
              ),
            ),

          // Touch layer
          _buildTouchLayer(boardSize),
        ],
      ),
    );

    if (widget.flipBoard) {
      boardStack = Transform.rotate(
        angle: 3.14159,
        child: boardStack,
      );
    }

    return Center(
      child: RepaintBoundary(
        child: boardStack,
      ),
    );
  }

  Widget _buildBasicBoard(double boardSize) {
    if (widget.animationEnabled && widget.selectedPiece != null) {
      return AnimatedBuilder(
        animation: _selectionPulseAnimation!,
        builder: (_, __) => _buildPaintedBoard(boardSize),
      );
    }
    return _buildPaintedBoard(boardSize);
  }

  Widget _buildPaintedBoard(double boardSize) {
    return Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.3),
            blurRadius: 10,
            offset: const Offset(0, 5),
          ),
        ],
      ),
      child: CustomPaint(
        painter: BoardPainter(
          boardState: widget.boardState,
          selectedPiece: widget.selectedPiece,
          validMoves: widget.validMoves,
          lastMoveFrom: widget.lastMoveFrom,
          lastMoveTo: widget.lastMoveTo,
          hidePiece: _animatingTo, // 隐藏目标位置的棋子，显示动画棋子
          theme: widget.theme,
          selectionPulse:
              widget.animationEnabled ? _selectionPulseAnimation?.value : null,
        ),
        size: Size(boardSize, boardSize),
      ),
    );
  }

  /// 构建移动中的棋子
  Widget _buildAnimatingPiece(double cellSize) {
    return AnimatedBuilder(
      animation: _moveAnimation!,
      builder: (context, child) {
        final offset = _moveAnimation!.value;
        return Positioned(
          left: offset.dx * cellSize,
          top: offset.dy * cellSize,
          child: SizedBox(
            width: cellSize,
            height: cellSize,
            child: CustomPaint(
              painter: _PiecePainter(
                piece: _animatingPiece!,
                cellSize: cellSize,
              ),
            ),
          ),
        );
      },
    );
  }

  /// 构建被吃的棋子（带消失动画）
  Widget _buildCapturingPiece(
    double cellSize,
    Position position,
    PieceType piece,
  ) {
    return AnimatedBuilder(
      key: ValueKey('captured-piece-${position.x}-${position.y}'),
      animation: _captureAnimationController!,
      builder: (context, child) {
        return Positioned(
          left: position.x * cellSize,
          top: position.y * cellSize,
          child: Opacity(
            opacity: _captureOpacityAnimation!.value,
            child: Transform.scale(
              scale: _captureScaleAnimation!.value,
              child: SizedBox(
                width: cellSize,
                height: cellSize,
                child: CustomPaint(
                  painter: _PiecePainter(
                    piece: piece,
                    cellSize: cellSize,
                  ),
                ),
              ),
            ),
          ),
        );
      },
    );
  }

  /// 构建触摸层
  Widget _buildCaptureParticles(
    double boardSize,
    double cellSize,
    Position position,
    PieceType piece,
  ) {
    return AnimatedBuilder(
      animation: _captureAnimationController!,
      builder: (context, child) {
        return CustomPaint(
          size: Size(boardSize, boardSize),
          painter: _ParticlePainter(
            position: position,
            piece: piece,
            progress: _captureAnimationController!.value,
            cellSize: cellSize,
            theme: widget.theme,
          ),
        );
      },
    );
  }

  Widget _buildTouchLayer(double boardSize) {
    return GestureDetector(
      onTapUp: (details) => _handleTap(details, boardSize),
      child: Container(color: Colors.transparent),
    );
  }

  /// 计算棋盘尺寸
  double _calculateBoardSize(BuildContext context) {
    final screenSize = MediaQuery.of(context).size;
    final maxSize = screenSize.width < screenSize.height
        ? screenSize.width
        : screenSize.height;

    return (maxSize * UIConstants.boardScreenRatio).clamp(
      UIConstants.boardMinSize,
      UIConstants.boardMaxSize,
    );
  }

  /// 处理点击事件
  void _handleTap(TapUpDetails details, double boardSize) {
    final cellSize = boardSize / GameConstants.boardSize;
    var localPos = details.localPosition;

    if (widget.flipBoard) {
      localPos = Offset(
        boardSize - localPos.dx,
        boardSize - localPos.dy,
      );
    }

    final x = (localPos.dx / cellSize).floor();
    final y = (localPos.dy / cellSize).floor();

    if (x >= 0 &&
        x < GameConstants.boardSize &&
        y >= 0 &&
        y < GameConstants.boardSize) {
      final position = Position(x, y);
      widget.onPositionTapped(position);
    }
  }
}

/// 单个棋子绘制器
class _ParticlePainter extends CustomPainter {
  final Position position;
  final PieceType piece;
  final double progress;
  final double cellSize;
  final BoardTheme? theme;

  _ParticlePainter({
    required this.position,
    required this.piece,
    required this.progress,
    required this.cellSize,
    this.theme,
  });

  @override
  void paint(Canvas canvas, Size size) {
    final center = Offset(
      position.x * cellSize + cellSize / 2,
      position.y * cellSize + cellSize / 2,
    );
    final color = piece == PieceType.black ? Colors.black87 : Colors.white;
    final accent = theme?.moveHintColor ?? Colors.tealAccent;
    const particleCount = 8;
    final maxRadius = cellSize * 0.6;
    final radius = maxRadius * progress;
    final alpha = (1.0 - progress).clamp(0.0, 1.0);

    for (var i = 0; i < particleCount; i++) {
      final angle = (i / particleCount) * math.pi * 2;
      final offset = Offset(
        math.cos(angle) * radius,
        math.sin(angle) * radius,
      );
      final paint = Paint()
        ..color = Color.lerp(color, accent, 0.6)!.withValues(alpha: alpha)
        ..style = PaintingStyle.fill;

      canvas.drawCircle(center + offset, cellSize * 0.06, paint);
    }
  }

  @override
  bool shouldRepaint(covariant _ParticlePainter oldDelegate) {
    return oldDelegate.progress != progress ||
        oldDelegate.position != position ||
        oldDelegate.piece != piece ||
        oldDelegate.cellSize != cellSize ||
        oldDelegate.theme != theme;
  }
}

class _PiecePainter extends CustomPainter {
  final PieceType piece;
  final double cellSize;

  _PiecePainter({
    required this.piece,
    required this.cellSize,
  });

  @override
  void paint(Canvas canvas, Size size) {
    final center = Offset(cellSize / 2, cellSize / 2);
    final radius = cellSize * 0.35;

    final paint = Paint()
      ..style = PaintingStyle.fill
      ..color = piece == PieceType.black ? Colors.black87 : Colors.white;

    // 绘制阴影
    final shadowPaint = Paint()
      ..color = Colors.black.withValues(alpha: 0.3)
      ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 3);

    canvas.drawCircle(
      center + const Offset(2, 2),
      radius,
      shadowPaint,
    );

    // 绘制棋子
    canvas.drawCircle(center, radius, paint);

    // 绘制高光
    final highlightPaint = Paint()
      ..style = PaintingStyle.fill
      ..color =
          Colors.white.withValues(alpha: piece == PieceType.black ? 0.2 : 0.4);

    canvas.drawCircle(
      center - Offset(radius * 0.3, radius * 0.3),
      radius * 0.4,
      highlightPaint,
    );

    // 绘制边框
    final borderPaint = Paint()
      ..style = PaintingStyle.stroke
      ..color =
          piece == PieceType.black ? Colors.grey.shade800 : Colors.grey.shade300
      ..strokeWidth = 2;

    canvas.drawCircle(center, radius, borderPaint);
  }

  @override
  bool shouldRepaint(_PiecePainter oldDelegate) {
    return oldDelegate.piece != piece || oldDelegate.cellSize != cellSize;
  }
}
