// Generated by Qoder AI (Model: claude-sonnet-4-5-20250929) - 2025-10-22
// Task: 实现棋盘Widget，集成BoardPainter并处理用户交互

import 'package:flutter/material.dart';
import '../../models/board_state.dart';
import '../../models/piece_type.dart';
import '../../models/position.dart';
import '../../constants/ui_constants.dart';
import '../../constants/game_constants.dart';
import '../../theme/theme_pack.dart';
import '../../l10n/app_localizations.dart';
import 'board_painter.dart';

/// 棋盘Widget
///
/// 集成BoardPainter进行绘制，并处理用户点击交互
class BoardWidget extends StatelessWidget {
  final BoardState boardState;
  final Position? selectedPiece;
  final List<Position> validMoves;
  final Position? lastMoveFrom;
  final Position? lastMoveTo;
  final Function(Position) onPositionTapped;
  final double? size;
  final ThemePack? themePack;

  /// 是否翻转棋盘视角（初始黑方在上，翻转后黑方在下）。
  final bool flipBoard;

  const BoardWidget({
    super.key,
    required this.boardState,
    required this.onPositionTapped,
    this.selectedPiece,
    this.validMoves = const [],
    this.lastMoveFrom,
    this.lastMoveTo,
    this.size,
    this.themePack,
    this.flipBoard = false,
  });

  @override
  Widget build(BuildContext context) {
    // 计算棋盘尺寸
    final boardSize = size ?? _calculateBoardSize(context);

    Widget boardVisual = ExcludeSemantics(
      child: CustomPaint(
        painter: BoardPainter(
          boardState: boardState,
          selectedPiece: selectedPiece,
          validMoves: validMoves,
          lastMoveFrom: lastMoveFrom,
          lastMoveTo: lastMoveTo,
          themePack: themePack,
        ),
        size: Size(boardSize, boardSize),
      ),
    );

    // 如果需要翻转视角，旋转180度
    if (flipBoard) {
      boardVisual = Transform.rotate(
        angle: 3.14159, // 180度 = π弧度
        child: boardVisual,
      );
    }

    final boardContent = Stack(
      children: [
        boardVisual,
        BoardSemanticsOverlay(
          boardState: boardState,
          selectedPiece: selectedPiece,
          validMoves: validMoves,
          lastMoveFrom: lastMoveFrom,
          lastMoveTo: lastMoveTo,
          flipBoard: flipBoard,
          onPositionTapped: onPositionTapped,
        ),
      ],
    );

    return Center(
      child: RepaintBoundary(
        // 添加 RepaintBoundary 优化渲染
        child: Container(
          width: boardSize,
          height: boardSize,
          decoration: BoxDecoration(
            boxShadow: [UIConstants.boardShadow],
          ),
          child: boardContent,
        ),
      ),
    );
  }

  /// 计算棋盘尺寸
  double _calculateBoardSize(BuildContext context) {
    final screenSize = MediaQuery.of(context).size;
    final maxSize = screenSize.width < screenSize.height
        ? screenSize.width
        : screenSize.height;

    // 留出边距，取屏幕最小边的指定比例
    return (maxSize * UIConstants.boardScreenRatio).clamp(
      UIConstants.boardMinSize,
      UIConstants.boardMaxSize,
    );
  }
}

/// Accessible interaction layer shared by static and animated board hosts.
class BoardSemanticsOverlay extends StatelessWidget {
  const BoardSemanticsOverlay({
    super.key,
    required this.boardState,
    required this.onPositionTapped,
    this.selectedPiece,
    this.validMoves = const [],
    this.lastMoveFrom,
    this.lastMoveTo,
    this.flipBoard = false,
  });

  final BoardState boardState;
  final Position? selectedPiece;
  final List<Position> validMoves;
  final Position? lastMoveFrom;
  final Position? lastMoveTo;
  final ValueChanged<Position> onPositionTapped;
  final bool flipBoard;

  @override
  Widget build(BuildContext context) {
    return GridView.count(
      crossAxisCount: GameConstants.boardSize,
      padding: EdgeInsets.zero,
      physics: const NeverScrollableScrollPhysics(),
      children: [
        for (var displayY = 0; displayY < GameConstants.boardSize; displayY++)
          for (var displayX = 0; displayX < GameConstants.boardSize; displayX++)
            _buildCell(context, displayX, displayY),
      ],
    );
  }

  Widget _buildCell(BuildContext context, int displayX, int displayY) {
    final logicalPosition = flipBoard
        ? Position(
            GameConstants.boardSize - displayX - 1,
            GameConstants.boardSize - displayY - 1,
          )
        : Position(displayX, displayY);
    final piece = boardState.getPiece(logicalPosition);
    final isSelected = selectedPiece == logicalPosition;
    final isValidMove = validMoves.contains(logicalPosition);
    final isSelectable = piece == boardState.currentPlayer;
    final isActionable = isSelectable || isValidMove;
    final l10n = AppLocalizations.of(context)!;

    return Semantics(
      label: _semanticLabel(
        l10n: l10n,
        locale: Localizations.localeOf(context),
        displayX: displayX,
        displayY: displayY,
        logicalPosition: logicalPosition,
        piece: piece,
        isSelected: isSelected,
        isValidMove: isValidMove,
        isSelectable: isSelectable,
      ),
      button: isActionable,
      enabled: isActionable,
      selected: isSelected,
      onTap: isActionable ? () => onPositionTapped(logicalPosition) : null,
      child: GestureDetector(
        behavior: HitTestBehavior.opaque,
        excludeFromSemantics: true,
        onTap: () => onPositionTapped(logicalPosition),
        child: const SizedBox.expand(),
      ),
    );
  }

  String _semanticLabel({
    required AppLocalizations l10n,
    required Locale locale,
    required int displayX,
    required int displayY,
    required Position logicalPosition,
    required PieceType piece,
    required bool isSelected,
    required bool isValidMove,
    required bool isSelectable,
  }) {
    final parts = <String>[
      l10n.boardCellPosition(displayY + 1, displayX + 1),
      switch (piece) {
        PieceType.black => l10n.blackSide,
        PieceType.white => l10n.whiteSide,
        PieceType.empty => l10n.boardEmptyPosition,
      },
    ];
    if (isSelected) parts.add(l10n.boardSelected);
    if (isValidMove) parts.add(l10n.boardLegalDestination);
    if (isSelectable) parts.add(l10n.boardSelectablePiece);
    if (logicalPosition == lastMoveFrom) {
      parts.add(l10n.boardPreviousMoveStart);
    }
    if (logicalPosition == lastMoveTo) {
      parts.add(l10n.boardPreviousMoveEnd);
    }
    return parts.join(_semanticSeparator(locale));
  }

  String _semanticSeparator(Locale locale) {
    return switch (locale.languageCode) {
      'zh' => '，',
      'ja' => '、',
      _ => ', ',
    };
  }
}
