// Generated by Qoder AI (Model: gemini-3-pro) - 2025-11-25
// Task: 创建先手方提示动画组件

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/scheduler.dart';
import '../../l10n/app_localizations.dart';
import '../../models/piece_type.dart';

/// 先手方指示器组件
///
/// 在双人对战开始时显示先手方信息的动画提示
class FirstPlayerIndicator extends StatefulWidget {
  /// 先手方（黑方或白方）
  final PieceType firstPlayer;

  /// 动画完成回调
  final VoidCallback? onAnimationComplete;

  /// 动画持续时间（毫秒）
  final int duration;

  const FirstPlayerIndicator({
    super.key,
    required this.firstPlayer,
    this.onAnimationComplete,
    this.duration = 2500,
  });

  @override
  State<FirstPlayerIndicator> createState() => _FirstPlayerIndicatorState();
}

class _FirstPlayerIndicatorState extends State<FirstPlayerIndicator>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  late Animation<double> _scaleAnimation;
  late Animation<double> _opacityAnimation;
  Timer? _completionTimer;
  Duration? _presentationDeadline;
  bool _reduceMotion = false;
  bool _completed = false;

  @override
  void initState() {
    super.initState();

    _controller = AnimationController(
      duration: Duration(milliseconds: widget.duration),
      vsync: this,
    );

    // 缩放动画：0.5 -> 1.2 -> 1.0 -> 0.8
    _scaleAnimation = TweenSequence<double>([
      TweenSequenceItem(
        tween: Tween<double>(begin: 0.5, end: 1.2)
            .chain(CurveTween(curve: Curves.easeOutBack)),
        weight: 30.0,
      ),
      TweenSequenceItem(
        tween: Tween<double>(begin: 1.2, end: 1.0)
            .chain(CurveTween(curve: Curves.easeInOut)),
        weight: 20.0,
      ),
      TweenSequenceItem(
        tween: ConstantTween<double>(1.0),
        weight: 30.0,
      ),
      TweenSequenceItem(
        tween: Tween<double>(begin: 1.0, end: 0.8)
            .chain(CurveTween(curve: Curves.easeIn)),
        weight: 20.0,
      ),
    ]).animate(_controller);

    // 不透明度动画：0.0 -> 1.0 -> 1.0 -> 0.0
    _opacityAnimation = TweenSequence<double>([
      TweenSequenceItem(
        tween: Tween<double>(begin: 0.0, end: 1.0)
            .chain(CurveTween(curve: Curves.easeIn)),
        weight: 20.0,
      ),
      TweenSequenceItem(
        tween: ConstantTween<double>(1.0),
        weight: 60.0,
      ),
      TweenSequenceItem(
        tween: Tween<double>(begin: 1.0, end: 0.0)
            .chain(CurveTween(curve: Curves.easeOut)),
        weight: 20.0,
      ),
    ]).animate(_controller);
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final reduceMotion =
        MediaQuery.maybeOf(context)?.disableAnimations ?? false;
    if (_presentationDeadline != null && reduceMotion == _reduceMotion) return;
    _reduceMotion = reduceMotion;
    _completionTimer?.cancel();
    _controller.stop();
    if (_completed) return;
    final frameTime = SchedulerBinding.instance.currentFrameTimeStamp;
    _presentationDeadline ??= frameTime + _controller.duration!;
    final remaining = _presentationDeadline! - frameTime;
    if (remaining <= Duration.zero) {
      _completionTimer = Timer(Duration.zero, _completePresentation);
    } else {
      _completionTimer = Timer(remaining, _completePresentation);
      if (!_reduceMotion) {
        _controller.value = (1 -
                remaining.inMicroseconds / _controller.duration!.inMicroseconds)
            .clamp(0.0, 1.0)
            .toDouble();
        _controller.forward();
      }
    }
  }

  void _completePresentation() {
    if (!mounted || _completed) return;
    _controller.stop();
    _controller.value = 1;
    setState(() => _completed = true);
    widget.onAnimationComplete?.call();
  }

  @override
  void dispose() {
    _completionTimer?.cancel();
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    final isBlack = widget.firstPlayer == PieceType.black;
    final playerName = isBlack ? l10n.blackSide : l10n.whiteSide;
    final firstPlayerMessage = l10n.firstPlayerAnnouncement(playerName);
    final gameStartingMessage = l10n.gameStarting;
    final semanticsLabel =
        switch (Localizations.localeOf(context).languageCode) {
      'en' => '$firstPlayerMessage. $gameStartingMessage',
      _ => '$firstPlayerMessage。$gameStartingMessage',
    };
    final playerColor = isBlack ? Colors.black : Colors.white;
    final backgroundColor = isBlack ? Colors.white : Colors.black87;

    return AnimatedBuilder(
      animation: _controller,
      builder: (context, child) {
        return Opacity(
          opacity:
              _reduceMotion ? (_completed ? 0 : 1) : _opacityAnimation.value,
          alwaysIncludeSemantics: true,
          child: Transform.scale(
            scale: _reduceMotion ? 1 : _scaleAnimation.value,
            child: Container(
              padding: const EdgeInsets.symmetric(
                horizontal: 48,
                vertical: 24,
              ),
              decoration: BoxDecoration(
                color: backgroundColor,
                borderRadius: BorderRadius.circular(16),
                boxShadow: [
                  BoxShadow(
                    color: playerColor.withValues(alpha: 0.3),
                    blurRadius: 20,
                    spreadRadius: 5,
                  ),
                ],
                border: Border.all(
                  color: playerColor.withValues(alpha: 0.5),
                  width: 2,
                ),
              ),
              child: Semantics(
                container: true,
                liveRegion: true,
                label: semanticsLabel,
                child: ExcludeSemantics(
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      // 棋子图标
                      Container(
                        width: 60,
                        height: 60,
                        decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          color: playerColor,
                          border: Border.all(
                            color: backgroundColor,
                            width: 3,
                          ),
                          boxShadow: [
                            BoxShadow(
                              color: playerColor.withValues(alpha: 0.5),
                              blurRadius: 10,
                              spreadRadius: 2,
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 16),
                      // 先手文本
                      Text(
                        firstPlayerMessage,
                        style: TextStyle(
                          fontSize: 28,
                          fontWeight: FontWeight.bold,
                          color: playerColor,
                          letterSpacing: 2,
                        ),
                      ),
                      const SizedBox(height: 8),
                      // 提示文本
                      Text(
                        gameStartingMessage,
                        style: TextStyle(
                          fontSize: 16,
                          color: playerColor.withValues(alpha: 0.7),
                          letterSpacing: 1,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        );
      },
    );
  }
}
